// Code generated by ent, DO NOT EDIT.

package variable

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldOrganizationID, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldApplicationID, v))
}

// ComponentID applies equality check predicate on the "component_id" field. It's identical to ComponentIDEQ.
func ComponentID(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldComponentID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldName, v))
}

// Sensitive applies equality check predicate on the "sensitive" field. It's identical to SensitiveEQ.
func Sensitive(v bool) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldSensitive, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldValue, v))
}

// EncryptedValue applies equality check predicate on the "encrypted_value" field. It's identical to EncryptedValueEQ.
func EncryptedValue(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldEncryptedValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ComponentIDEQ applies the EQ predicate on the "component_id" field.
func ComponentIDEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldComponentID, v))
}

// ComponentIDNEQ applies the NEQ predicate on the "component_id" field.
func ComponentIDNEQ(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldComponentID, v))
}

// ComponentIDIn applies the In predicate on the "component_id" field.
func ComponentIDIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldComponentID, vs...))
}

// ComponentIDNotIn applies the NotIn predicate on the "component_id" field.
func ComponentIDNotIn(vs ...uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldComponentID, vs...))
}

// ComponentIDGT applies the GT predicate on the "component_id" field.
func ComponentIDGT(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldComponentID, v))
}

// ComponentIDGTE applies the GTE predicate on the "component_id" field.
func ComponentIDGTE(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldComponentID, v))
}

// ComponentIDLT applies the LT predicate on the "component_id" field.
func ComponentIDLT(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldComponentID, v))
}

// ComponentIDLTE applies the LTE predicate on the "component_id" field.
func ComponentIDLTE(v uuid.UUID) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldComponentID, v))
}

// ComponentIDIsNil applies the IsNil predicate on the "component_id" field.
func ComponentIDIsNil() predicate.Variable {
	return predicate.Variable(sql.FieldIsNull(FieldComponentID))
}

// ComponentIDNotNil applies the NotNil predicate on the "component_id" field.
func ComponentIDNotNil() predicate.Variable {
	return predicate.Variable(sql.FieldNotNull(FieldComponentID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Variable {
	return predicate.Variable(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Variable {
	return predicate.Variable(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Variable {
	return predicate.Variable(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Variable {
	return predicate.Variable(sql.FieldContainsFold(FieldName, v))
}

// SensitiveEQ applies the EQ predicate on the "sensitive" field.
func SensitiveEQ(v bool) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldSensitive, v))
}

// SensitiveNEQ applies the NEQ predicate on the "sensitive" field.
func SensitiveNEQ(v bool) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldSensitive, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.Variable {
	return predicate.Variable(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.Variable {
	return predicate.Variable(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.Variable {
	return predicate.Variable(sql.FieldHasSuffix(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.Variable {
	return predicate.Variable(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.Variable {
	return predicate.Variable(sql.FieldNotNull(FieldValue))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.Variable {
	return predicate.Variable(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.Variable {
	return predicate.Variable(sql.FieldContainsFold(FieldValue, v))
}

// EncryptedValueEQ applies the EQ predicate on the "encrypted_value" field.
func EncryptedValueEQ(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldEncryptedValue, v))
}

// EncryptedValueNEQ applies the NEQ predicate on the "encrypted_value" field.
func EncryptedValueNEQ(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldEncryptedValue, v))
}

// EncryptedValueIn applies the In predicate on the "encrypted_value" field.
func EncryptedValueIn(vs ...[]byte) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldEncryptedValue, vs...))
}

// EncryptedValueNotIn applies the NotIn predicate on the "encrypted_value" field.
func EncryptedValueNotIn(vs ...[]byte) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldEncryptedValue, vs...))
}

// EncryptedValueGT applies the GT predicate on the "encrypted_value" field.
func EncryptedValueGT(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldEncryptedValue, v))
}

// EncryptedValueGTE applies the GTE predicate on the "encrypted_value" field.
func EncryptedValueGTE(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldEncryptedValue, v))
}

// EncryptedValueLT applies the LT predicate on the "encrypted_value" field.
func EncryptedValueLT(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldEncryptedValue, v))
}

// EncryptedValueLTE applies the LTE predicate on the "encrypted_value" field.
func EncryptedValueLTE(v []byte) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldEncryptedValue, v))
}

// EncryptedValueIsNil applies the IsNil predicate on the "encrypted_value" field.
func EncryptedValueIsNil() predicate.Variable {
	return predicate.Variable(sql.FieldIsNull(FieldEncryptedValue))
}

// EncryptedValueNotNil applies the NotNil predicate on the "encrypted_value" field.
func EncryptedValueNotNil() predicate.Variable {
	return predicate.Variable(sql.FieldNotNull(FieldEncryptedValue))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Variable {
	return predicate.Variable(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Variable {
	return predicate.Variable(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Variable {
	return predicate.Variable(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.Variable {
	return predicate.Variable(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.Variable {
	return predicate.Variable(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Variable) predicate.Variable {
	return predicate.Variable(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Variable) predicate.Variable {
	return predicate.Variable(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Variable) predicate.Variable {
	return predicate.Variable(sql.NotPredicates(p))
}
