//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClusterStatus.
const (
	ClusterStatusConnected ClusterStatus = "connected"
	ClusterStatusError     ClusterStatus = "error"
	ClusterStatusPending   ClusterStatus = "pending"
)

// Valid indicates whether the value is a known member of the ClusterStatus enum.
func (e ClusterStatus) Valid() bool {
	switch e {
	case ClusterStatusConnected:
		return true
	case ClusterStatusError:
		return true
	case ClusterStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ConnectionMethod.
const (
	Aks        ConnectionMethod = "aks"
	Eks        ConnectionMethod = "eks"
	Gke        ConnectionMethod = "gke"
	InCluster  ConnectionMethod = "in_cluster"
	Kubeconfig ConnectionMethod = "kubeconfig"
	Token      ConnectionMethod = "token"
)

// Valid indicates whether the value is a known member of the ConnectionMethod enum.
func (e ConnectionMethod) Valid() bool {
	switch e {
	case Aks:
		return true
	case Eks:
		return true
	case Gke:
		return true
	case InCluster:
		return true
	case Kubeconfig:
		return true
	case Token:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Member Role = "member"
	Owner  Role = "owner"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Member:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Cluster defines model for Cluster.
type Cluster struct {
	// Config Non-secret per-method parameters (region, project, …).
	Config map[string]string `json:"config"`

	// ConnectionMethod How Spacefleet connects to the cluster.
	//   - in_cluster: Spacefleet runs in this cluster; use its service account.
	//   - kubeconfig: a supplied kubeconfig with embedded static credentials.
	//   - token: explicit API URL + CA + ServiceAccount bearer token.
	//   - eks/gke/aks: cloud-native auth (credentials minted at connect time).
	ConnectionMethod ConnectionMethod `json:"connection_method"`
	CreatedAt        time.Time        `json:"created_at"`

	// Endpoint API server URL (display); may be empty or discovered.
	Endpoint *string            `json:"endpoint,omitempty"`
	Id       openapi_types.UUID `json:"id"`

	// K8sVersion Server version reported by the last successful probe.
	K8sVersion    *string    `json:"k8s_version,omitempty"`
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	Name          string     `json:"name"`

	// Status Result of the most recent connectivity probe.
	Status ClusterStatus `json:"status"`

	// StatusMessage Human-readable detail when status is error.
	StatusMessage *string   `json:"status_message,omitempty"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// ClusterCreateRequest A flat object: only the fields relevant to the chosen connection_method
// need be set; the server validates per method. Secret fields (kubeconfig,
// token, cloud credentials) are encrypted at rest and never returned.
type ClusterCreateRequest struct {
	AksClusterName *string `json:"aks_cluster_name,omitempty"`
	AwsAccessKeyId *string `json:"aws_access_key_id,omitempty"`
	AwsRegion      *string `json:"aws_region,omitempty"`

	// AwsRoleArn Optional role to assume after authenticating.
	AwsRoleArn          *string `json:"aws_role_arn,omitempty"`
	AwsSecretAccessKey  *string `json:"aws_secret_access_key,omitempty"`
	AwsSessionToken     *string `json:"aws_session_token,omitempty"`
	AzureClientId       *string `json:"azure_client_id,omitempty"`
	AzureClientSecret   *string `json:"azure_client_secret,omitempty"`
	AzureResourceGroup  *string `json:"azure_resource_group,omitempty"`
	AzureSubscriptionId *string `json:"azure_subscription_id,omitempty"`
	AzureTenantId       *string `json:"azure_tenant_id,omitempty"`

	// Ca PEM-encoded CA certificate bundle (token method).
	Ca *string `json:"ca,omitempty"`

	// ConnectionMethod How Spacefleet connects to the cluster.
	//   - in_cluster: Spacefleet runs in this cluster; use its service account.
	//   - kubeconfig: a supplied kubeconfig with embedded static credentials.
	//   - token: explicit API URL + CA + ServiceAccount bearer token.
	//   - eks/gke/aks: cloud-native auth (credentials minted at connect time).
	ConnectionMethod ConnectionMethod `json:"connection_method"`
	EksClusterName   *string          `json:"eks_cluster_name,omitempty"`

	// Endpoint API server URL (token method).
	Endpoint    *string `json:"endpoint,omitempty"`
	GcpLocation *string `json:"gcp_location,omitempty"`
	GcpProject  *string `json:"gcp_project,omitempty"`

	// GcpServiceAccountKey GCP service-account JSON key.
	GcpServiceAccountKey *string `json:"gcp_service_account_key,omitempty"`
	GkeClusterName       *string `json:"gke_cluster_name,omitempty"`

	// InsecureSkipTls Disable TLS verification (token method; use sparingly).
	InsecureSkipTls *bool `json:"insecure_skip_tls,omitempty"`

	// Kubeconfig Full kubeconfig YAML with embedded static credentials.
	Kubeconfig *string `json:"kubeconfig,omitempty"`
	Name       string  `json:"name"`

	// Token ServiceAccount bearer token (token method).
	Token *string `json:"token,omitempty"`
}

// ClusterStatus Result of the most recent connectivity probe.
type ClusterStatus string

// ClusterUpdateRequest All fields optional. Set name to rename; supply any credential field to
// re-encrypt and re-probe. The connection method is fixed at registration.
type ClusterUpdateRequest struct {
	AksClusterName       *string `json:"aks_cluster_name,omitempty"`
	AwsAccessKeyId       *string `json:"aws_access_key_id,omitempty"`
	AwsRegion            *string `json:"aws_region,omitempty"`
	AwsRoleArn           *string `json:"aws_role_arn,omitempty"`
	AwsSecretAccessKey   *string `json:"aws_secret_access_key,omitempty"`
	AwsSessionToken      *string `json:"aws_session_token,omitempty"`
	AzureClientId        *string `json:"azure_client_id,omitempty"`
	AzureClientSecret    *string `json:"azure_client_secret,omitempty"`
	AzureResourceGroup   *string `json:"azure_resource_group,omitempty"`
	AzureSubscriptionId  *string `json:"azure_subscription_id,omitempty"`
	AzureTenantId        *string `json:"azure_tenant_id,omitempty"`
	Ca                   *string `json:"ca,omitempty"`
	EksClusterName       *string `json:"eks_cluster_name,omitempty"`
	Endpoint             *string `json:"endpoint,omitempty"`
	GcpLocation          *string `json:"gcp_location,omitempty"`
	GcpProject           *string `json:"gcp_project,omitempty"`
	GcpServiceAccountKey *string `json:"gcp_service_account_key,omitempty"`
	GkeClusterName       *string `json:"gke_cluster_name,omitempty"`
	InsecureSkipTls      *bool   `json:"insecure_skip_tls,omitempty"`
	Kubeconfig           *string `json:"kubeconfig,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Token                *string `json:"token,omitempty"`
}

// ConnectionMethod How Spacefleet connects to the cluster.
//   - in_cluster: Spacefleet runs in this cluster; use its service account.
//   - kubeconfig: a supplied kubeconfig with embedded static credentials.
//   - token: explicit API URL + CA + ServiceAccount bearer token.
//   - eks/gke/aks: cloud-native auth (credentials minted at connect time).
type ConnectionMethod string

// ContainerStatus The live state of a single container in a pod.
type ContainerStatus struct {
	Image        *string `json:"image,omitempty"`
	Name         string  `json:"name"`
	Ready        bool    `json:"ready"`
	RestartCount int     `json:"restart_count"`
	Started      *bool   `json:"started,omitempty"`

	// State Running, Waiting, or Terminated.
	State        *string `json:"state,omitempty"`
	StateMessage *string `json:"state_message,omitempty"`

	// StateReason For waiting/terminated containers (e.g. CrashLoopBackOff).
	StateReason *string `json:"state_reason,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Me defines model for Me.
type Me struct {
	Organizations []OrgMembership `json:"organizations"`
	User          User            `json:"user"`
}

// Namespace A single Kubernetes namespace, as seen live on the cluster.
type Namespace struct {
	CreatedAt time.Time         `json:"created_at"`
	Labels    map[string]string `json:"labels"`
	Name      string            `json:"name"`

	// Status The namespace phase (Active, or Terminating while deleting).
	Status string `json:"status"`
}

// Node A single Kubernetes node, as seen live on the cluster.
type Node struct {
	// Allocatable A node's compute resources, as reported by Kubernetes.
	Allocatable  *NodeResources `json:"allocatable,omitempty"`
	Architecture *string        `json:"architecture,omitempty"`

	// Capacity A node's compute resources, as reported by Kubernetes.
	Capacity         *NodeResources  `json:"capacity,omitempty"`
	Conditions       []NodeCondition `json:"conditions"`
	ContainerRuntime *string         `json:"container_runtime,omitempty"`
	CreatedAt        time.Time       `json:"created_at"`
	ExternalIp       *string         `json:"external_ip,omitempty"`
	Hostname         *string         `json:"hostname,omitempty"`

	// InstanceType From the node.kubernetes.io/instance-type label.
	InstanceType    *string           `json:"instance_type,omitempty"`
	InternalIp      *string           `json:"internal_ip,omitempty"`
	KernelVersion   *string           `json:"kernel_version,omitempty"`
	KubeletVersion  *string           `json:"kubelet_version,omitempty"`
	Labels          map[string]string `json:"labels"`
	Name            string            `json:"name"`
	OperatingSystem *string           `json:"operating_system,omitempty"`
	OsImage         *string           `json:"os_image,omitempty"`
	PodCidr         *string           `json:"pod_cidr,omitempty"`
	ProviderId      *string           `json:"provider_id,omitempty"`

	// Ready Whether the node's Ready condition is True.
	Ready bool `json:"ready"`

	// Region From the topology.kubernetes.io/region label.
	Region *string `json:"region,omitempty"`

	// Roles Roles derived from node-role.kubernetes.io/* labels.
	Roles  []string    `json:"roles"`
	Taints []NodeTaint `json:"taints"`

	// Unschedulable Whether the node is cordoned (spec.unschedulable).
	Unschedulable bool `json:"unschedulable"`

	// Zone From the topology.kubernetes.io/zone label.
	Zone *string `json:"zone,omitempty"`
}

// NodeCondition defines model for NodeCondition.
type NodeCondition struct {
	LastTransitionTime *time.Time `json:"last_transition_time,omitempty"`
	Message            *string    `json:"message,omitempty"`
	Reason             *string    `json:"reason,omitempty"`

	// Status True, False, or Unknown.
	Status string `json:"status"`

	// Type e.g. Ready, MemoryPressure, DiskPressure.
	Type string `json:"type"`
}

// NodeResources A node's compute resources, as reported by Kubernetes.
type NodeResources struct {
	// Cpu CPU quantity (e.g. "4" or "3920m").
	Cpu string `json:"cpu"`

	// Memory Memory quantity (e.g. "16331752Ki").
	Memory string `json:"memory"`

	// Pods Maximum number of pods.
	Pods string `json:"pods"`
}

// NodeTaint defines model for NodeTaint.
type NodeTaint struct {
	// Effect NoSchedule, PreferNoSchedule, or NoExecute.
	Effect string  `json:"effect"`
	Key    string  `json:"key"`
	Value  *string `json:"value,omitempty"`
}

// OrgMembership defines model for OrgMembership.
type OrgMembership struct {
	Organization Organization `json:"organization"`
	Role         Role         `json:"role"`
}

// Organization defines model for Organization.
type Organization struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// OrganizationCreateRequest defines model for OrganizationCreateRequest.
type OrganizationCreateRequest struct {
	Name string `json:"name"`
}

// Pod A single Kubernetes pod, as seen live on the cluster.
type Pod struct {
	Conditions []PodCondition    `json:"conditions"`
	Containers []ContainerStatus `json:"containers"`
	CreatedAt  time.Time         `json:"created_at"`
	HostIp     *string           `json:"host_ip,omitempty"`
	Labels     map[string]string `json:"labels"`
	Name       string            `json:"name"`
	Namespace  string            `json:"namespace"`
	NodeName   *string           `json:"node_name,omitempty"`

	// Phase Pending, Running, Succeeded, Failed, or Unknown.
	Phase string  `json:"phase"`
	PodIp *string `json:"pod_ip,omitempty"`

	// QosClass Guaranteed, Burstable, or BestEffort.
	QosClass *string `json:"qos_class,omitempty"`

	// Ready Ready/total container count (e.g. "2/3").
	Ready           string `json:"ready"`
	ReadyContainers int    `json:"ready_containers"`

	// Restarts Total container restarts across the pod.
	Restarts       int     `json:"restarts"`
	ServiceAccount *string `json:"service_account,omitempty"`

	// Status The display status kubectl shows, which folds container state into
	// the phase (e.g. Running, CrashLoopBackOff, Completed, Terminating).
	Status          string `json:"status"`
	TotalContainers int    `json:"total_containers"`
}

// PodCondition defines model for PodCondition.
type PodCondition struct {
	LastTransitionTime *time.Time `json:"last_transition_time,omitempty"`
	Message            *string    `json:"message,omitempty"`
	Reason             *string    `json:"reason,omitempty"`

	// Status True, False, or Unknown.
	Status string `json:"status"`

	// Type e.g. Ready, Initialized, ContainersReady, PodScheduled.
	Type string `json:"type"`
}

// Role defines model for Role.
type Role string

// User defines model for User.
type User struct {
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`
}

// ClusterID defines model for ClusterID.
type ClusterID = openapi_types.UUID

// OrganizationID defines model for OrganizationID.
type OrganizationID = openapi_types.UUID

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreateRequest

// UpdateClusterJSONRequestBody defines body for UpdateCluster for application/json ContentType.
type UpdateClusterJSONRequestBody = ClusterUpdateRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = OrganizationCreateRequest

// RenameOrganizationJSONRequestBody defines body for RenameOrganization for application/json ContentType.
type RenameOrganizationJSONRequestBody = OrganizationCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the clusters registered to the current organization
	// (GET /api/clusters)
	ListClusters(w http.ResponseWriter, r *http.Request)
	// Register a Kubernetes cluster in the current organization
	// (POST /api/clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /api/clusters/{id})
	DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterID)
	// Get a cluster
	// (GET /api/clusters/{id})
	GetCluster(w http.ResponseWriter, r *http.Request, id ClusterID)
	// Update a cluster (name and/or credentials)
	// (PATCH /api/clusters/{id})
	UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterID)
	// List the Kubernetes namespaces of a cluster
	// (GET /api/clusters/{id}/namespaces)
	ListClusterNamespaces(w http.ResponseWriter, r *http.Request, id ClusterID)
	// List the Kubernetes nodes of a cluster
	// (GET /api/clusters/{id}/nodes)
	ListClusterNodes(w http.ResponseWriter, r *http.Request, id ClusterID)
	// List the Kubernetes pods of a cluster
	// (GET /api/clusters/{id}/pods)
	ListClusterPods(w http.ResponseWriter, r *http.Request, id ClusterID)
	// Re-probe a cluster's connectivity
	// (POST /api/clusters/{id}/test)
	TestCluster(w http.ResponseWriter, r *http.Request, id ClusterID)
	// Liveness probe
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// The current user and their organization memberships
	// (GET /api/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Create an organization (the caller becomes its owner)
	// (POST /api/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Rename an organization (owners only)
	// (PATCH /api/organizations/{id})
	RenameOrganization(w http.ResponseWriter, r *http.Request, id OrganizationID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCluster operation middleware
func (siw *ServerInterfaceWrapper) UpdateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusterNamespaces operation middleware
func (siw *ServerInterfaceWrapper) ListClusterNamespaces(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusterNamespaces(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusterNodes operation middleware
func (siw *ServerInterfaceWrapper) ListClusterNodes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusterNodes(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClusterPods operation middleware
func (siw *ServerInterfaceWrapper) ListClusterPods(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusterPods(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestCluster operation middleware
func (siw *ServerInterfaceWrapper) TestCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ClusterID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestCluster(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameOrganization operation middleware
func (siw *ServerInterfaceWrapper) RenameOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameOrganization(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/clusters", wrapper.ListClusters)
	m.HandleFunc("POST "+options.BaseURL+"/api/clusters", wrapper.CreateCluster)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/clusters/{id}", wrapper.DeleteCluster)
	m.HandleFunc("GET "+options.BaseURL+"/api/clusters/{id}", wrapper.GetCluster)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/clusters/{id}", wrapper.UpdateCluster)
	m.HandleFunc("GET "+options.BaseURL+"/api/clusters/{id}/namespaces", wrapper.ListClusterNamespaces)
	m.HandleFunc("GET "+options.BaseURL+"/api/clusters/{id}/nodes", wrapper.ListClusterNodes)
	m.HandleFunc("GET "+options.BaseURL+"/api/clusters/{id}/pods", wrapper.ListClusterPods)
	m.HandleFunc("POST "+options.BaseURL+"/api/clusters/{id}/test", wrapper.TestCluster)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/me", wrapper.GetMe)
	m.HandleFunc("POST "+options.BaseURL+"/api/organizations", wrapper.CreateOrganization)
	m.HandleFunc("PATCH "+options.BaseURL+"/api/organizations/{id}", wrapper.RenameOrganization)

	return m
}

type ErrorJSONResponse Error

type ListClustersRequestObject struct {
}

type ListClustersResponseObject interface {
	VisitListClustersResponse(w http.ResponseWriter) error
}

type ListClusters200JSONResponse []Cluster

func (response ListClusters200JSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListClustersdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListClustersdefaultJSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateClusterRequestObject struct {
	Body *CreateClusterJSONRequestBody
}

type CreateClusterResponseObject interface {
	VisitCreateClusterResponse(w http.ResponseWriter) error
}

type CreateCluster201JSONResponse Cluster

func (response CreateCluster201JSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateClusterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateClusterdefaultJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteClusterRequestObject struct {
	Id ClusterID `json:"id"`
}

type DeleteClusterResponseObject interface {
	VisitDeleteClusterResponse(w http.ResponseWriter) error
}

type DeleteCluster204Response struct {
}

func (response DeleteCluster204Response) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteClusterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteClusterdefaultJSONResponse) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetClusterRequestObject struct {
	Id ClusterID `json:"id"`
}

type GetClusterResponseObject interface {
	VisitGetClusterResponse(w http.ResponseWriter) error
}

type GetCluster200JSONResponse Cluster

func (response GetCluster200JSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetClusterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetClusterdefaultJSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateClusterRequestObject struct {
	Id   ClusterID `json:"id"`
	Body *UpdateClusterJSONRequestBody
}

type UpdateClusterResponseObject interface {
	VisitUpdateClusterResponse(w http.ResponseWriter) error
}

type UpdateCluster200JSONResponse Cluster

func (response UpdateCluster200JSONResponse) VisitUpdateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateClusterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateClusterdefaultJSONResponse) VisitUpdateClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListClusterNamespacesRequestObject struct {
	Id ClusterID `json:"id"`
}

type ListClusterNamespacesResponseObject interface {
	VisitListClusterNamespacesResponse(w http.ResponseWriter) error
}

type ListClusterNamespaces200JSONResponse []Namespace

func (response ListClusterNamespaces200JSONResponse) VisitListClusterNamespacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListClusterNamespacesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListClusterNamespacesdefaultJSONResponse) VisitListClusterNamespacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListClusterNodesRequestObject struct {
	Id ClusterID `json:"id"`
}

type ListClusterNodesResponseObject interface {
	VisitListClusterNodesResponse(w http.ResponseWriter) error
}

type ListClusterNodes200JSONResponse []Node

func (response ListClusterNodes200JSONResponse) VisitListClusterNodesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListClusterNodesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListClusterNodesdefaultJSONResponse) VisitListClusterNodesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListClusterPodsRequestObject struct {
	Id ClusterID `json:"id"`
}

type ListClusterPodsResponseObject interface {
	VisitListClusterPodsResponse(w http.ResponseWriter) error
}

type ListClusterPods200JSONResponse []Pod

func (response ListClusterPods200JSONResponse) VisitListClusterPodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListClusterPodsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListClusterPodsdefaultJSONResponse) VisitListClusterPodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type TestClusterRequestObject struct {
	Id ClusterID `json:"id"`
}

type TestClusterResponseObject interface {
	VisitTestClusterResponse(w http.ResponseWriter) error
}

type TestCluster200JSONResponse Cluster

func (response TestCluster200JSONResponse) VisitTestClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TestClusterdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response TestClusterdefaultJSONResponse) VisitTestClusterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetMedefaultJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateOrganizationRequestObject struct {
	Body *CreateOrganizationJSONRequestBody
}

type CreateOrganizationResponseObject interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization201JSONResponse Organization

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganizationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateOrganizationdefaultJSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RenameOrganizationRequestObject struct {
	Id   OrganizationID `json:"id"`
	Body *RenameOrganizationJSONRequestBody
}

type RenameOrganizationResponseObject interface {
	VisitRenameOrganizationResponse(w http.ResponseWriter) error
}

type RenameOrganization200JSONResponse Organization

func (response RenameOrganization200JSONResponse) VisitRenameOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RenameOrganizationdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RenameOrganizationdefaultJSONResponse) VisitRenameOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List the clusters registered to the current organization
	// (GET /api/clusters)
	ListClusters(ctx context.Context, request ListClustersRequestObject) (ListClustersResponseObject, error)
	// Register a Kubernetes cluster in the current organization
	// (POST /api/clusters)
	CreateCluster(ctx context.Context, request CreateClusterRequestObject) (CreateClusterResponseObject, error)
	// Delete a cluster
	// (DELETE /api/clusters/{id})
	DeleteCluster(ctx context.Context, request DeleteClusterRequestObject) (DeleteClusterResponseObject, error)
	// Get a cluster
	// (GET /api/clusters/{id})
	GetCluster(ctx context.Context, request GetClusterRequestObject) (GetClusterResponseObject, error)
	// Update a cluster (name and/or credentials)
	// (PATCH /api/clusters/{id})
	UpdateCluster(ctx context.Context, request UpdateClusterRequestObject) (UpdateClusterResponseObject, error)
	// List the Kubernetes namespaces of a cluster
	// (GET /api/clusters/{id}/namespaces)
	ListClusterNamespaces(ctx context.Context, request ListClusterNamespacesRequestObject) (ListClusterNamespacesResponseObject, error)
	// List the Kubernetes nodes of a cluster
	// (GET /api/clusters/{id}/nodes)
	ListClusterNodes(ctx context.Context, request ListClusterNodesRequestObject) (ListClusterNodesResponseObject, error)
	// List the Kubernetes pods of a cluster
	// (GET /api/clusters/{id}/pods)
	ListClusterPods(ctx context.Context, request ListClusterPodsRequestObject) (ListClusterPodsResponseObject, error)
	// Re-probe a cluster's connectivity
	// (POST /api/clusters/{id}/test)
	TestCluster(ctx context.Context, request TestClusterRequestObject) (TestClusterResponseObject, error)
	// Liveness probe
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// The current user and their organization memberships
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Create an organization (the caller becomes its owner)
	// (POST /api/organizations)
	CreateOrganization(ctx context.Context, request CreateOrganizationRequestObject) (CreateOrganizationResponseObject, error)
	// Rename an organization (owners only)
	// (PATCH /api/organizations/{id})
	RenameOrganization(ctx context.Context, request RenameOrganizationRequestObject) (RenameOrganizationResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListClusters operation middleware
func (sh *strictHandler) ListClusters(w http.ResponseWriter, r *http.Request) {
	var request ListClustersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusters(ctx, request.(ListClustersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClustersResponseObject); ok {
		if err := validResponse.VisitListClustersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCluster operation middleware
func (sh *strictHandler) CreateCluster(w http.ResponseWriter, r *http.Request) {
	var request CreateClusterRequestObject

	var body CreateClusterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCluster(ctx, request.(CreateClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateClusterResponseObject); ok {
		if err := validResponse.VisitCreateClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCluster operation middleware
func (sh *strictHandler) DeleteCluster(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request DeleteClusterRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCluster(ctx, request.(DeleteClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteClusterResponseObject); ok {
		if err := validResponse.VisitDeleteClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCluster operation middleware
func (sh *strictHandler) GetCluster(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request GetClusterRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCluster(ctx, request.(GetClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClusterResponseObject); ok {
		if err := validResponse.VisitGetClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCluster operation middleware
func (sh *strictHandler) UpdateCluster(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request UpdateClusterRequestObject

	request.Id = id

	var body UpdateClusterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCluster(ctx, request.(UpdateClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateClusterResponseObject); ok {
		if err := validResponse.VisitUpdateClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListClusterNamespaces operation middleware
func (sh *strictHandler) ListClusterNamespaces(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request ListClusterNamespacesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusterNamespaces(ctx, request.(ListClusterNamespacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusterNamespaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClusterNamespacesResponseObject); ok {
		if err := validResponse.VisitListClusterNamespacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListClusterNodes operation middleware
func (sh *strictHandler) ListClusterNodes(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request ListClusterNodesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusterNodes(ctx, request.(ListClusterNodesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusterNodes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClusterNodesResponseObject); ok {
		if err := validResponse.VisitListClusterNodesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListClusterPods operation middleware
func (sh *strictHandler) ListClusterPods(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request ListClusterPodsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusterPods(ctx, request.(ListClusterPodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusterPods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClusterPodsResponseObject); ok {
		if err := validResponse.VisitListClusterPodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TestCluster operation middleware
func (sh *strictHandler) TestCluster(w http.ResponseWriter, r *http.Request, id ClusterID) {
	var request TestClusterRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TestCluster(ctx, request.(TestClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TestCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TestClusterResponseObject); ok {
		if err := validResponse.VisitTestClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrganization operation middleware
func (sh *strictHandler) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	var request CreateOrganizationRequestObject

	var body CreateOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrganization(ctx, request.(CreateOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrganizationResponseObject); ok {
		if err := validResponse.VisitCreateOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RenameOrganization operation middleware
func (sh *strictHandler) RenameOrganization(w http.ResponseWriter, r *http.Request, id OrganizationID) {
	var request RenameOrganizationRequestObject

	request.Id = id

	var body RenameOrganizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RenameOrganization(ctx, request.(RenameOrganizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RenameOrganization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RenameOrganizationResponseObject); ok {
		if err := validResponse.VisitRenameOrganizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x86XIbOZL/q2TU/x8x0g4P2Z7Zg/7klrs93vGhkOSY3Rh2cMCqJIkhCqgGUJLZHYrY",
	"p9kH2yfZSAB1sVAUZUvujt39ZLEKRx4/5IUs/5KkKi+URGlNMvslKZhmOVrU7te5KI1F/fY1/eAymSUF",
	"s5tklEiWYzJLeJaMEo0/lVxjlsysLnGUmHSDOaMZK6VzZpNZUpZupN0VNMtYzeU6ubsbJR/1mkn+M7Nc",
	"yafa5Y4mm0JJg46p77VWmv5IlbQoLf3JikLw1JEx/btRkp41O/x/jatklvy/aSOrqX9rpn41t0uGJtW8",
	"oEWSmd8Gqp0dt2FOS7JO5FoVqC331KVKrvja0ZRlnNZi4qIzYo+//X0/KDk2mGq0UKAe52g3KoNGr3Ci",
	"cc2VHEGh1d8xtSP4r//4z9NJIzm1pMe0cqqkxJQWXvh17pPGeT3hvR9Pi2hkFrMFsx1tZczi2PIc+yob",
	"JSizQnGvmy57ry7egkF9gxo+Xb6Dk4ybQrDd6UvI2Q6WCJgXdgdKQ8ZNqm5QYzaJbcGzI8AzSrb/bBY3",
	"qA33oOgSc+UJCe9BY6G0xQyWO7AbBMGMBVOmKRqzKgUJfIlRYmjkIt1guj0sKFkKwZYCq1PQW8gfmQhI",
	"jGW2NPfqz8Pyyg+upy1yNIatsS+BP5U5k2ONLCOyIEPLuIDbDUrwU4EbQDoKUb7LInsgNu7apuCv3jY4",
	"pmNordkeVeeqA8fO/j9G8B/Ece6mXOJPJZoYJGElmAU/bQZKCq/+FUeRGdAo8IZJC1a5x+lGGZTQo3Yu",
	"JRJ2EAzal25oAPoNE5zoNHSiwY+ewJU/5GGXk225RM/kaC6t2qIcQSpUmUGqMUNpORPmFJhGQJnqXUFA",
	"ZZYslAUmM5BIe2m0pZaYTeYyGe3ZJrY1i9SLZDEINHZrFsxBfrHF3cIfs+gob4eGXyuBC6Yjx+5j4e0i",
	"0BASKzOmzBHYyqIGVtoNsUvmXK6jsKPlvY1skTpIiEFDx3vhhBof9XOpcZEKjtIOctwe4zc/ME6jUaVO",
	"cbHWqiwODDTlshbN4a0tSjZMXsr6cr74/v0YZaoyzOD8FaSEhBXJFWFZykwgnDiZBEieRmX9KD4Ej0He",
	"8U7jfqrXabEQykcE0c1oQHCgg+9pS54iYUyV0lYg69L25vwCwsBxGAj/evXxA2xxFydti/fLgkuDqcPH",
	"lhcLK0x/49fcOJt9/e6KPJjXLLmxjnheQmkQTMFoZbFrS2uplEAmnZesjU9/nx9KIaAZAP/+6v07uOV2",
	"A5gvMSNwkZXmadtQRTmvuM3Z53co13aTzJ6fnY2SnMvq97PItPrc9p03T/FVkPkSmUYNnvd7EbLnhgY9",
	"0AGvclV75C5dl2hKYUGtnAvIlSEbnaK0tcu44XbXBBMoy5xoKFBmRFtNBpIDdL63RUYjlkDGJ+cCh52b",
	"EJWLUcHskuuxQCyT7dVIf70EUxaF2AGTu5Ye/VSwai41joPfcd5G49hzANfkE2vBBZlT2LDinysXtebG",
	"aofO35Zf+j/Pcqxn6Vvrh5r0b2qjH9Hq3mctH93M9U1V3wTt+9h+YK9u4apgKa4EYm16TB3EelFM5hJg",
	"DFxWspm1J+lSGuAS7Iabaob3J9yayulBkHxYqpHNDJg3Khyztv+413X4hZw4ZoCfKbPnFigGIOf/ewpl",
	"fg8HrH9YALdmut7ilG3NzEfSY8ksv0EXYcJJa0vIuQzhdBAUUPZy6o1VZaAbKSUdDFSqc2cicVBLRmTU",
	"4mZbScu4HPYfZE8FkUmiQfIjDAw5b2dm/VzSCoNCudS4a0x5HhK943NLSv92cahTdsG0XTgpt4aQvNao",
	"Q4pJSXN8vuMh4iNLKblcj+AvjFv3h9JwjTrnkvK5aPTglmpnsgMjNDITS/Z/UBpu/XZTW2/VyNTACU7W",
	"EzjXzGzeKVV8x9Ltx9Xq+PDBy3FfaLEQoq5h7RePsjhnw1zvUeJWaMbH9v4TMkE2aH/zpsJQAV5tIwje",
	"2zDMim30HvubqFbB0MPVYn5vWeOjXr8ni6HNhhdJYxCZ1mzn6hDG1+IOLfKJxuyT7yaO9siKMfOB5WjI",
	"NMbqB+F4/rlcopZIib6sho+AkalE6c+0kh3z2zu9X1JsE2yJ3lUdXXLssXdE3alvpWomodgwg3DyioJb",
	"7BxmLtdwu+GutiSQfh5/nuriT+CwU/yJKimcnyP0o7KHqoYJF6z48t1hqBEdlyFOc2U4ptMNt5jaUuNA",
	"kFWwlNvdg1dOlfQ6P/400Rrn1bTYaapN4kKX0qEuSvKX1IU/W9SSiQWPR64bZeyh6MwymeLCv+nZd61y",
	"p0HS7WRb63rC1bSaOqap4OAULyrLw/RtaU3RLij3h5RLAvrBMU96YmkZd+4WZmcs5vFBZjEcKBQqW6Q8",
	"0/GXWt3wDPVQulAHE13t/GWDdkMRWlDQ7wxc0kioAUwp47UuMV6haJK6Aa1bVSih1rs9zft5B1RO6WAs",
	"i6fHkKHmN5jBinYhssc0fG+Lf/Cru5pHfQCHFFgfMjph9mGH9pqmRN2fpGFZKSrjdFj2JOlU6UxJzODE",
	"FJhOOisMFIl+VhIfrgCaNSj+w3FUl61KVS13EGTYsYJHOYnG/PUiFHeVYzWTxg1YVPbvy+5zDoWrTaB6",
	"vNelXeAHJoz3sp/kVqpbGQV23Eq6ENedvBG8x1zp3YVGY0qNI3jNzbb6db+y3NvRoQCw66wifjkYAoJ7",
	"aRGq0oZxnrl9G9d47kjIVJT9tc8vPsFPJZOW212I6+fJH+YJCW2evPiX52f5PImXjnMnlf6SXlr9VZ/9",
	"44sXz/7pj8//zIdWLFQWYf89+8zzMgdZUmRLeR6Nu1/uxG9NZVh8SPreYvQwjqtVqKns3z1f+QOHI7jQ",
	"uELdfqI0fFDff8a0tPFb0KHayw0T5RG5C00fVbTFOOqmAQdziyMyimZs8AL3zSGX0CO6s2lYZ4D2DnFf",
	"H/YfeQE+GCc87t3tA25l26LoXc125fJFpbSYU4nRcRGrm8WShUJlD03jHh6VX6jsuKD8+CX3S02xVb8A",
	"eBSkDwXITxrZynYO3n+rMhwu7boMNXJF6i9dRlBXpK7KNEXMMCM/ywX9e4+jpXB5QBw/KbNIBTMR8/+m",
	"ZJpJi7TBd6U2LrF0e32Hxn6/Wilt4wFrPMB2Pn1qlWWiVSf01dHKVT2fvhjyUW7VRRdk/VpfqGzFIpO9",
	"jauRwFKtjHHHJdQrIyXEbhH/wYWI0ERUtay42qwVYDbq1ozgdsPTDayUyEyLQF9d5dKquXTE+RKGj48q",
	"MOzXAkdwrvJCoCWttUocoVIcqelbJu6RajwGbrBeYbdVD2kKjXtKi+zYUlq7kNIJmNuj74meO2bqf3Pw",
	"/FZyy5ngPxMUaktrwtsLlVWBU/YYofRliE/q0uytdIXL3MVD0YuGTybWn4g54yJeXsmO6/nshQB+yT7V",
	"d66gslKRy6nr6wt3obNSPittXTqxopjA9Ya7zjPXROVyAnefrku7mQG3c7lGidq1VNGQN6pqDzG2XBo4",
	"EXw5ZQWfrlFO1urU3VjTwOtdgVeOkLn0F65ARBs4KfnU6NRN8u5zkk2sOXW2AP6Wsy3CGuXfQo8SZu4e",
	"YTKXc1ldQeVMsjXmtCY30I4LxylKq3k66zw1rpfLbnAurSrGAm9QgL+KdfQyKA1qyEtjYYlCyTVYBSf0",
	"asNuEAwK1yRwCpRhW0XDvSlzInSs5AhLpayxmhVeVFcXr/wNnItfSq2JXrdRkBHXc9kmE/I65DbBynFL",
	"YExaSnt18TYZJXXJKzmbPJuchWKUZAVPZsmLydnkBRkzZjcOiY7AEEG5B2uMpCQf9XpsUlVgNnMkd0gj",
	"hLAtSl+fodf/Nm5Hl+O3r2GDLHMXnaHfrn3tRwrwbXNcpqLMMPPXnVj3/XqOQ0lNybdZMkvecWPPK7r3",
	"mpOfn509qDX5uDgu3Dr24rd+13JFV8VHpWG1l+9kuGKlsEM71zzV/dGjxJR5zigxdgJox78mdHigxqy+",
	"YB7YuFCxLpUrq3Q4y61WEt+NarpXtb4B8gaFKuqOFHd1O5fk6PxZ53mOGWcWRWi0MW16R6FLkss1cFsf",
	"B7dAKdyVRYsKb5VjQPDJy3l9J6x9GvOd8vHZo/SnR1tY77p2mNznXQ+Izx6bhgN4awHgq9F1GZYC1s7B",
	"guoO4/pu1LUq0194dufRRjGbKxJ0NPjaPW802P584q9x4psh0+bzirsfe+L/Q6QoFXjw1Hy9pDz1wCrh",
	"uD4Xb0S7bL5B+yQ8nn0LiF03B/erJfaGAoz2agWz6aavKd9U1zEav/OXumRepu7DkHFobjGd5hW4JkPy",
	"gH44uHKNd2R0ur13c+mb75rGO9PpvIuaJE/4Yyn7ycxZt2nxKHN29i3NWahgfTXePJ8N5OCkjaF2Y/+A",
	"8ZrWeeBxIdKy5JTm0oYuuq0DowbFhnxt1o2DZDaXghtrXGdXs6evdtWLtOzxq4u3ofUzcBbiVHKiLN1Q",
	"XvcSmISy+V0P3fl+VAZ/PHt+T4D1oWH/V7Rcx93Q1Rn7EXHadc+wBC4fLTaLNaMY301W278ByKnsm6KN",
	"tvv1geaY/s1jTGVfAi/H25Mgy+nuGFBVd2DfBlO0W1V5ZEI8yKLN5R7S4FGBdkGC+K3j7MJ/tvMwmDkV",
	"PwXKnDaPAZmtLpGiSeYlBmx5NDXoiuMJNK40mk0/Lw0ZYU/L12j+Z8TZPiWu+M8Cw4+Q2fnItVGku/xv",
	"Popp9Lqpm1SHEprQxvqEsgo7REQVms8pqPeE7noovkGJxvjiQ8OWr4ZHbeClK0l4rLU+gcTMVefc1943",
	"3HDlqhYMhEqZAI2p0hkoCSuujZ1Lw9cbOwLmyoV1na9bdrQb3DUVRe9cry5e0T7G9frPpVVN3XBGRq/6",
	"Kru9DplbyJEFoptqpb9CmEslEZa4UppeEtlVcTJiId+gfY9Pqc33GA349yugrWrnV+P9erDECkMV1gYq",
	"vU7pyqjFalAf97oQniBzG761/8bVqG7rRl+l7fcBil+fyHmO6SR0NHfiPAMTAjUsMVU5+vjDXc+cDiiz",
	"rkrVxYeuSi/dF3l7Kn2YN9n7fzmeKpv/Skyc/TqYeKzk3uupjwmnfOP+H4FTT4y/nPKaK7VIZsk0ufvx",
	"7r8DAAD//9ZDjFi9RQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
