// Code generated by ent, DO NOT EDIT.

package planpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldOrganizationID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldDescription, v))
}

// Rego applies equality check predicate on the "rego" field. It's identical to RegoEQ.
func Rego(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldRego, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldEnabled, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldApplicationID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContainsFold(FieldDescription, v))
}

// RegoEQ applies the EQ predicate on the "rego" field.
func RegoEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldRego, v))
}

// RegoNEQ applies the NEQ predicate on the "rego" field.
func RegoNEQ(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldRego, v))
}

// RegoIn applies the In predicate on the "rego" field.
func RegoIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldRego, vs...))
}

// RegoNotIn applies the NotIn predicate on the "rego" field.
func RegoNotIn(vs ...string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldRego, vs...))
}

// RegoGT applies the GT predicate on the "rego" field.
func RegoGT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldRego, v))
}

// RegoGTE applies the GTE predicate on the "rego" field.
func RegoGTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldRego, v))
}

// RegoLT applies the LT predicate on the "rego" field.
func RegoLT(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldRego, v))
}

// RegoLTE applies the LTE predicate on the "rego" field.
func RegoLTE(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldRego, v))
}

// RegoContains applies the Contains predicate on the "rego" field.
func RegoContains(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContains(FieldRego, v))
}

// RegoHasPrefix applies the HasPrefix predicate on the "rego" field.
func RegoHasPrefix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasPrefix(FieldRego, v))
}

// RegoHasSuffix applies the HasSuffix predicate on the "rego" field.
func RegoHasSuffix(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldHasSuffix(FieldRego, v))
}

// RegoEqualFold applies the EqualFold predicate on the "rego" field.
func RegoEqualFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEqualFold(FieldRego, v))
}

// RegoContainsFold applies the ContainsFold predicate on the "rego" field.
func RegoContainsFold(v string) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldContainsFold(FieldRego, v))
}

// EnforcementEQ applies the EQ predicate on the "enforcement" field.
func EnforcementEQ(v Enforcement) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldEnforcement, v))
}

// EnforcementNEQ applies the NEQ predicate on the "enforcement" field.
func EnforcementNEQ(v Enforcement) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldEnforcement, v))
}

// EnforcementIn applies the In predicate on the "enforcement" field.
func EnforcementIn(vs ...Enforcement) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldEnforcement, vs...))
}

// EnforcementNotIn applies the NotIn predicate on the "enforcement" field.
func EnforcementNotIn(vs ...Enforcement) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldEnforcement, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldEnabled, v))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...uuid.UUID) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ApplicationIDIsNil applies the IsNil predicate on the "application_id" field.
func ApplicationIDIsNil() predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIsNull(FieldApplicationID))
}

// ApplicationIDNotNil applies the NotNil predicate on the "application_id" field.
func ApplicationIDNotNil() predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotNull(FieldApplicationID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.PlanPolicy {
	return predicate.PlanPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.PlanPolicy {
	return predicate.PlanPolicy(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.PlanPolicy {
	return predicate.PlanPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.PlanPolicy {
	return predicate.PlanPolicy(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlanPolicy) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlanPolicy) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlanPolicy) predicate.PlanPolicy {
	return predicate.PlanPolicy(sql.NotPredicates(p))
}
