// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "imported", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"helm"}, Default: "helm"},
		{Name: "chart_source", Type: field.TypeEnum, Enums: []string{"http_repo", "oci", "git"}},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "values", Type: field.TypeString, Nullable: true},
		{Name: "values_sources", Type: field.TypeJSON, Nullable: true},
		{Name: "release_name", Type: field.TypeString, Nullable: true},
		{Name: "target_namespace", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "deploying", "deployed", "failed", "uninstalling", "uninstalled"}, Default: "pending"},
		{Name: "status_message", Type: field.TypeString, Nullable: true},
		{Name: "job_id", Type: field.TypeString, Nullable: true},
		{Name: "last_run_name", Type: field.TypeString, Nullable: true},
		{Name: "sync_status", Type: field.TypeEnum, Enums: []string{"unknown", "refreshing", "synced", "out_of_sync", "error"}, Default: "unknown"},
		{Name: "sync_message", Type: field.TypeString, Nullable: true},
		{Name: "last_diff", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "desired_chart_revision", Type: field.TypeString, Nullable: true},
		{Name: "desired_values_revision", Type: field.TypeString, Nullable: true},
		{Name: "last_refreshed_at", Type: field.TypeTime, Nullable: true},
		{Name: "sync_job_id", Type: field.TypeString, Nullable: true},
		{Name: "sync_run_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "target_cluster_id", Type: field.TypeUUID},
		{Name: "runner_cluster_id", Type: field.TypeUUID},
		{Name: "chart_credential_id", Type: field.TypeUUID, Nullable: true},
		{Name: "github_installation_id", Type: field.TypeUUID, Nullable: true},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "applications_organizations_organization",
				Columns:    []*schema.Column{ApplicationsColumns[24]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "applications_clusters_target_cluster",
				Columns:    []*schema.Column{ApplicationsColumns[25]},
				RefColumns: []*schema.Column{ClustersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "applications_clusters_runner_cluster",
				Columns:    []*schema.Column{ApplicationsColumns[26]},
				RefColumns: []*schema.Column{ClustersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "applications_chart_credentials_chart_credential",
				Columns:    []*schema.Column{ApplicationsColumns[27]},
				RefColumns: []*schema.Column{ChartCredentialsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "applications_github_installations_github_installation",
				Columns:    []*schema.Column{ApplicationsColumns[28]},
				RefColumns: []*schema.Column{GithubInstallationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "application_organization_id",
				Unique:  false,
				Columns: []*schema.Column{ApplicationsColumns[24]},
			},
			{
				Name:    "application_organization_id_name",
				Unique:  true,
				Columns: []*schema.Column{ApplicationsColumns[24], ApplicationsColumns[1]},
			},
		},
	}
	// ChartCredentialsColumns holds the columns for the "chart_credentials" table.
	ChartCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "encrypted_password", Type: field.TypeBytes, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// ChartCredentialsTable holds the schema information for the "chart_credentials" table.
	ChartCredentialsTable = &schema.Table{
		Name:       "chart_credentials",
		Columns:    ChartCredentialsColumns,
		PrimaryKey: []*schema.Column{ChartCredentialsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chart_credentials_organizations_organization",
				Columns:    []*schema.Column{ChartCredentialsColumns[6]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "chartcredential_organization_id",
				Unique:  false,
				Columns: []*schema.Column{ChartCredentialsColumns[6]},
			},
			{
				Name:    "chartcredential_organization_id_name",
				Unique:  true,
				Columns: []*schema.Column{ChartCredentialsColumns[6], ChartCredentialsColumns[1]},
			},
		},
	}
	// ClustersColumns holds the columns for the "clusters" table.
	ClustersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "connection_method", Type: field.TypeEnum, Enums: []string{"in_cluster", "kubeconfig", "token", "eks", "gke", "aks"}},
		{Name: "endpoint", Type: field.TypeString, Nullable: true},
		{Name: "config", Type: field.TypeJSON, Nullable: true},
		{Name: "encrypted_credentials", Type: field.TypeBytes, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "connected", "error"}, Default: "pending"},
		{Name: "status_message", Type: field.TypeString, Nullable: true},
		{Name: "k8s_version", Type: field.TypeString, Nullable: true},
		{Name: "last_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// ClustersTable holds the schema information for the "clusters" table.
	ClustersTable = &schema.Table{
		Name:       "clusters",
		Columns:    ClustersColumns,
		PrimaryKey: []*schema.Column{ClustersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clusters_organizations_organization",
				Columns:    []*schema.Column{ClustersColumns[12]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "cluster_organization_id",
				Unique:  false,
				Columns: []*schema.Column{ClustersColumns[12]},
			},
			{
				Name:    "cluster_organization_id_name",
				Unique:  true,
				Columns: []*schema.Column{ClustersColumns[12], ClustersColumns[1]},
			},
		},
	}
	// DeploymentsColumns holds the columns for the "deployments" table.
	DeploymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"deploy", "upgrade", "uninstall"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "succeeded", "failed"}, Default: "running"},
		{Name: "forced", Type: field.TypeBool, Default: false},
		{Name: "message", Type: field.TypeString, Nullable: true},
		{Name: "job_id", Type: field.TypeString, Nullable: true},
		{Name: "run_name", Type: field.TypeString, Nullable: true},
		{Name: "logs", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "chart_revision", Type: field.TypeString, Nullable: true},
		{Name: "values_revision", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "application_id", Type: field.TypeUUID},
	}
	// DeploymentsTable holds the schema information for the "deployments" table.
	DeploymentsTable = &schema.Table{
		Name:       "deployments",
		Columns:    DeploymentsColumns,
		PrimaryKey: []*schema.Column{DeploymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deployments_organizations_organization",
				Columns:    []*schema.Column{DeploymentsColumns[13]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "deployments_applications_application",
				Columns:    []*schema.Column{DeploymentsColumns[14]},
				RefColumns: []*schema.Column{ApplicationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "deployment_organization_id",
				Unique:  false,
				Columns: []*schema.Column{DeploymentsColumns[13]},
			},
			{
				Name:    "deployment_application_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeploymentsColumns[14], DeploymentsColumns[10]},
			},
			{
				Name:    "deployment_organization_id_job_id",
				Unique:  false,
				Columns: []*schema.Column{DeploymentsColumns[13], DeploymentsColumns[5]},
			},
		},
	}
	// GithubInstallationsColumns holds the columns for the "github_installations" table.
	GithubInstallationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "installation_id", Type: field.TypeInt64},
		{Name: "account_login", Type: field.TypeString, Nullable: true},
		{Name: "account_type", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// GithubInstallationsTable holds the schema information for the "github_installations" table.
	GithubInstallationsTable = &schema.Table{
		Name:       "github_installations",
		Columns:    GithubInstallationsColumns,
		PrimaryKey: []*schema.Column{GithubInstallationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "github_installations_organizations_organization",
				Columns:    []*schema.Column{GithubInstallationsColumns[6]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "githubinstallation_organization_id",
				Unique:  false,
				Columns: []*schema.Column{GithubInstallationsColumns[6]},
			},
			{
				Name:    "githubinstallation_organization_id_installation_id",
				Unique:  true,
				Columns: []*schema.Column{GithubInstallationsColumns[6], GithubInstallationsColumns[1]},
			},
		},
	}
	// InvitationsColumns holds the columns for the "invitations" table.
	InvitationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "editor", "viewer"}, Default: "viewer"},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "accepted", "revoked"}, Default: "pending"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "accepted_at", Type: field.TypeTime, Nullable: true},
		{Name: "invited_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// InvitationsTable holds the schema information for the "invitations" table.
	InvitationsTable = &schema.Table{
		Name:       "invitations",
		Columns:    InvitationsColumns,
		PrimaryKey: []*schema.Column{InvitationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitations_organizations_organization",
				Columns:    []*schema.Column{InvitationsColumns[9]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invitation_organization_id",
				Unique:  false,
				Columns: []*schema.Column{InvitationsColumns[9]},
			},
		},
	}
	// MembershipsColumns holds the columns for the "memberships" table.
	MembershipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "editor", "viewer"}, Default: "viewer"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// MembershipsTable holds the schema information for the "memberships" table.
	MembershipsTable = &schema.Table{
		Name:       "memberships",
		Columns:    MembershipsColumns,
		PrimaryKey: []*schema.Column{MembershipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "memberships_users_user",
				Columns:    []*schema.Column{MembershipsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "memberships_organizations_organization",
				Columns:    []*schema.Column{MembershipsColumns[4]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "membership_user_id_organization_id",
				Unique:  true,
				Columns: []*schema.Column{MembershipsColumns[3], MembershipsColumns[4]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
	}
	// TektonInstallationsColumns holds the columns for the "tekton_installations" table.
	TektonInstallationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"not_installed", "installing", "installed", "upgrading", "failed", "uninstalling"}, Default: "not_installed"},
		{Name: "installed_version", Type: field.TypeString, Nullable: true},
		{Name: "status_message", Type: field.TypeString, Nullable: true},
		{Name: "job_id", Type: field.TypeString, Nullable: true},
		{Name: "last_checked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "cluster_id", Type: field.TypeUUID, Unique: true},
	}
	// TektonInstallationsTable holds the schema information for the "tekton_installations" table.
	TektonInstallationsTable = &schema.Table{
		Name:       "tekton_installations",
		Columns:    TektonInstallationsColumns,
		PrimaryKey: []*schema.Column{TektonInstallationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tekton_installations_clusters_tekton",
				Columns:    []*schema.Column{TektonInstallationsColumns[9]},
				RefColumns: []*schema.Column{ClustersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tektoninstallation_cluster_id",
				Unique:  true,
				Columns: []*schema.Column{TektonInstallationsColumns[9]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "oidc_subject", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		ChartCredentialsTable,
		ClustersTable,
		DeploymentsTable,
		GithubInstallationsTable,
		InvitationsTable,
		MembershipsTable,
		OrganizationsTable,
		TektonInstallationsTable,
		UsersTable,
	}
)

func init() {
	ApplicationsTable.ForeignKeys[0].RefTable = OrganizationsTable
	ApplicationsTable.ForeignKeys[1].RefTable = ClustersTable
	ApplicationsTable.ForeignKeys[2].RefTable = ClustersTable
	ApplicationsTable.ForeignKeys[3].RefTable = ChartCredentialsTable
	ApplicationsTable.ForeignKeys[4].RefTable = GithubInstallationsTable
	ChartCredentialsTable.ForeignKeys[0].RefTable = OrganizationsTable
	ClustersTable.ForeignKeys[0].RefTable = OrganizationsTable
	DeploymentsTable.ForeignKeys[0].RefTable = OrganizationsTable
	DeploymentsTable.ForeignKeys[1].RefTable = ApplicationsTable
	GithubInstallationsTable.ForeignKeys[0].RefTable = OrganizationsTable
	GithubInstallationsTable.Annotation = &entsql.Annotation{
		Table: "github_installations",
	}
	InvitationsTable.ForeignKeys[0].RefTable = OrganizationsTable
	MembershipsTable.ForeignKeys[0].RefTable = UsersTable
	MembershipsTable.ForeignKeys[1].RefTable = OrganizationsTable
	TektonInstallationsTable.ForeignKeys[0].RefTable = ClustersTable
}
