// Code generated by ent, DO NOT EDIT.

package componentrun

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the componentrun type in the database.
	Label = "component_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldWorkflowRunID holds the string denoting the workflow_run_id field in the database.
	FieldWorkflowRunID = "workflow_run_id"
	// FieldComponentID holds the string denoting the component_id field in the database.
	FieldComponentID = "component_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldRunName holds the string denoting the run_name field in the database.
	FieldRunName = "run_name"
	// FieldLogs holds the string denoting the logs field in the database.
	FieldLogs = "logs"
	// FieldApprovedBy holds the string denoting the approved_by field in the database.
	FieldApprovedBy = "approved_by"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// FieldChartRevision holds the string denoting the chart_revision field in the database.
	FieldChartRevision = "chart_revision"
	// FieldValuesRevision holds the string denoting the values_revision field in the database.
	FieldValuesRevision = "values_revision"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeWorkflowRun holds the string denoting the workflow_run edge name in mutations.
	EdgeWorkflowRun = "workflow_run"
	// Table holds the table name of the componentrun in the database.
	Table = "component_runs"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "component_runs"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
	// WorkflowRunTable is the table that holds the workflow_run relation/edge.
	WorkflowRunTable = "component_runs"
	// WorkflowRunInverseTable is the table name for the WorkflowRun entity.
	// It exists in this package in order to avoid circular dependency with the "workflowrun" package.
	WorkflowRunInverseTable = "workflow_runs"
	// WorkflowRunColumn is the table column denoting the workflow_run relation/edge.
	WorkflowRunColumn = "workflow_run_id"
)

// Columns holds all SQL columns for componentrun fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldWorkflowRunID,
	FieldComponentID,
	FieldName,
	FieldType,
	FieldStatus,
	FieldMessage,
	FieldRunName,
	FieldLogs,
	FieldApprovedBy,
	FieldApprovedAt,
	FieldChartRevision,
	FieldValuesRevision,
	FieldCreatedAt,
	FieldStartedAt,
	FieldFinishedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultApprovedBy holds the default value on creation for the "approved_by" field.
	DefaultApprovedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending          Status = "pending"
	StatusRunning          Status = "running"
	StatusSucceeded        Status = "succeeded"
	StatusFailed           Status = "failed"
	StatusSkipped          Status = "skipped"
	StatusAwaitingApproval Status = "awaiting_approval"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusRunning, StatusSucceeded, StatusFailed, StatusSkipped, StatusAwaitingApproval:
		return nil
	default:
		return fmt.Errorf("componentrun: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ComponentRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByWorkflowRunID orders the results by the workflow_run_id field.
func ByWorkflowRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowRunID, opts...).ToFunc()
}

// ByComponentID orders the results by the component_id field.
func ByComponentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComponentID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByRunName orders the results by the run_name field.
func ByRunName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunName, opts...).ToFunc()
}

// ByLogs orders the results by the logs field.
func ByLogs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogs, opts...).ToFunc()
}

// ByApprovedBy orders the results by the approved_by field.
func ByApprovedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedBy, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByChartRevision orders the results by the chart_revision field.
func ByChartRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChartRevision, opts...).ToFunc()
}

// ByValuesRevision orders the results by the values_revision field.
func ByValuesRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValuesRevision, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByWorkflowRunField orders the results by workflow_run field.
func ByWorkflowRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowRunStep(), sql.OrderByField(field, opts...))
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
	)
}
func newWorkflowRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowRunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, WorkflowRunTable, WorkflowRunColumn),
	)
}
