// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/application"
	"github.com/spacefleet/spacefleet/ent/chartcredential"
	"github.com/spacefleet/spacefleet/ent/cluster"
	"github.com/spacefleet/spacefleet/ent/component"
	"github.com/spacefleet/spacefleet/ent/componentgroup"
	"github.com/spacefleet/spacefleet/ent/githubinstallation"
	"github.com/spacefleet/spacefleet/ent/organization"
)

// ComponentCreate is the builder for creating a Component entity.
type ComponentCreate struct {
	config
	mutation *ComponentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrganizationID sets the "organization_id" field.
func (_c *ComponentCreate) SetOrganizationID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetApplicationID sets the "application_id" field.
func (_c *ComponentCreate) SetApplicationID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ComponentCreate) SetName(v string) *ComponentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ComponentCreate) SetType(v component.Type) *ComponentCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableType(v *component.Type) *ComponentCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *ComponentCreate) SetConfig(v map[string]string) *ComponentCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetDependsOn sets the "depends_on" field.
func (_c *ComponentCreate) SetDependsOn(v []uuid.UUID) *ComponentCreate {
	_c.mutation.SetDependsOn(v)
	return _c
}

// SetContinueOnFailure sets the "continue_on_failure" field.
func (_c *ComponentCreate) SetContinueOnFailure(v bool) *ComponentCreate {
	_c.mutation.SetContinueOnFailure(v)
	return _c
}

// SetNillableContinueOnFailure sets the "continue_on_failure" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableContinueOnFailure(v *bool) *ComponentCreate {
	if v != nil {
		_c.SetContinueOnFailure(*v)
	}
	return _c
}

// SetRequiresApproval sets the "requires_approval" field.
func (_c *ComponentCreate) SetRequiresApproval(v bool) *ComponentCreate {
	_c.mutation.SetRequiresApproval(v)
	return _c
}

// SetNillableRequiresApproval sets the "requires_approval" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableRequiresApproval(v *bool) *ComponentCreate {
	if v != nil {
		_c.SetRequiresApproval(*v)
	}
	return _c
}

// SetTargetClusterID sets the "target_cluster_id" field.
func (_c *ComponentCreate) SetTargetClusterID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetTargetClusterID(v)
	return _c
}

// SetNillableTargetClusterID sets the "target_cluster_id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableTargetClusterID(v *uuid.UUID) *ComponentCreate {
	if v != nil {
		_c.SetTargetClusterID(*v)
	}
	return _c
}

// SetTargetNamespace sets the "target_namespace" field.
func (_c *ComponentCreate) SetTargetNamespace(v string) *ComponentCreate {
	_c.mutation.SetTargetNamespace(v)
	return _c
}

// SetNillableTargetNamespace sets the "target_namespace" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableTargetNamespace(v *string) *ComponentCreate {
	if v != nil {
		_c.SetTargetNamespace(*v)
	}
	return _c
}

// SetChartCredentialID sets the "chart_credential_id" field.
func (_c *ComponentCreate) SetChartCredentialID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetChartCredentialID(v)
	return _c
}

// SetNillableChartCredentialID sets the "chart_credential_id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableChartCredentialID(v *uuid.UUID) *ComponentCreate {
	if v != nil {
		_c.SetChartCredentialID(*v)
	}
	return _c
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (_c *ComponentCreate) SetGithubInstallationID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetGithubInstallationID(v)
	return _c
}

// SetNillableGithubInstallationID sets the "github_installation_id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableGithubInstallationID(v *uuid.UUID) *ComponentCreate {
	if v != nil {
		_c.SetGithubInstallationID(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *ComponentCreate) SetPosition(v map[string]float64) *ComponentCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ComponentCreate) SetGroupID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableGroupID(v *uuid.UUID) *ComponentCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ComponentCreate) SetCreatedAt(v time.Time) *ComponentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableCreatedAt(v *time.Time) *ComponentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ComponentCreate) SetUpdatedAt(v time.Time) *ComponentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableUpdatedAt(v *time.Time) *ComponentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ComponentCreate) SetID(v uuid.UUID) *ComponentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableID(v *uuid.UUID) *ComponentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *ComponentCreate) SetOrganization(v *Organization) *ComponentCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetApplication sets the "application" edge to the Application entity.
func (_c *ComponentCreate) SetApplication(v *Application) *ComponentCreate {
	return _c.SetApplicationID(v.ID)
}

// SetTargetCluster sets the "target_cluster" edge to the Cluster entity.
func (_c *ComponentCreate) SetTargetCluster(v *Cluster) *ComponentCreate {
	return _c.SetTargetClusterID(v.ID)
}

// SetChartCredential sets the "chart_credential" edge to the ChartCredential entity.
func (_c *ComponentCreate) SetChartCredential(v *ChartCredential) *ComponentCreate {
	return _c.SetChartCredentialID(v.ID)
}

// SetGithubInstallation sets the "github_installation" edge to the GitHubInstallation entity.
func (_c *ComponentCreate) SetGithubInstallation(v *GitHubInstallation) *ComponentCreate {
	return _c.SetGithubInstallationID(v.ID)
}

// SetGroup sets the "group" edge to the ComponentGroup entity.
func (_c *ComponentCreate) SetGroup(v *ComponentGroup) *ComponentCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the ComponentMutation object of the builder.
func (_c *ComponentCreate) Mutation() *ComponentMutation {
	return _c.mutation
}

// Save creates the Component in the database.
func (_c *ComponentCreate) Save(ctx context.Context) (*Component, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ComponentCreate) SaveX(ctx context.Context) *Component {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ComponentCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := component.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.ContinueOnFailure(); !ok {
		v := component.DefaultContinueOnFailure
		_c.mutation.SetContinueOnFailure(v)
	}
	if _, ok := _c.mutation.RequiresApproval(); !ok {
		v := component.DefaultRequiresApproval
		_c.mutation.SetRequiresApproval(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := component.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := component.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := component.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ComponentCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Component.organization_id"`)}
	}
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "Component.application_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Component.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := component.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Component.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Component.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := component.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Component.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContinueOnFailure(); !ok {
		return &ValidationError{Name: "continue_on_failure", err: errors.New(`ent: missing required field "Component.continue_on_failure"`)}
	}
	if _, ok := _c.mutation.RequiresApproval(); !ok {
		return &ValidationError{Name: "requires_approval", err: errors.New(`ent: missing required field "Component.requires_approval"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Component.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Component.updated_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Component.organization"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "Component.application"`)}
	}
	return nil
}

func (_c *ComponentCreate) sqlSave(ctx context.Context) (*Component, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ComponentCreate) createSpec() (*Component, *sqlgraph.CreateSpec) {
	var (
		_node = &Component{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(component.Table, sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(component.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(component.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(component.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.DependsOn(); ok {
		_spec.SetField(component.FieldDependsOn, field.TypeJSON, value)
		_node.DependsOn = value
	}
	if value, ok := _c.mutation.ContinueOnFailure(); ok {
		_spec.SetField(component.FieldContinueOnFailure, field.TypeBool, value)
		_node.ContinueOnFailure = value
	}
	if value, ok := _c.mutation.RequiresApproval(); ok {
		_spec.SetField(component.FieldRequiresApproval, field.TypeBool, value)
		_node.RequiresApproval = value
	}
	if value, ok := _c.mutation.TargetNamespace(); ok {
		_spec.SetField(component.FieldTargetNamespace, field.TypeString, value)
		_node.TargetNamespace = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(component.FieldPosition, field.TypeJSON, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(component.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(component.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.OrganizationTable,
			Columns: []string{component.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.ApplicationTable,
			Columns: []string{component.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetClusterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.TargetClusterTable,
			Columns: []string{component.TargetClusterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cluster.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetClusterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChartCredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.ChartCredentialTable,
			Columns: []string{component.ChartCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chartcredential.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChartCredentialID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GithubInstallationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.GithubInstallationTable,
			Columns: []string{component.GithubInstallationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubinstallation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GithubInstallationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   component.GroupTable,
			Columns: []string{component.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(componentgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Component.Create().
//		SetOrganizationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComponentUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComponentCreate) OnConflict(opts ...sql.ConflictOption) *ComponentUpsertOne {
	_c.conflict = opts
	return &ComponentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Component.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComponentCreate) OnConflictColumns(columns ...string) *ComponentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComponentUpsertOne{
		create: _c,
	}
}

type (
	// ComponentUpsertOne is the builder for "upsert"-ing
	//  one Component node.
	ComponentUpsertOne struct {
		create *ComponentCreate
	}

	// ComponentUpsert is the "OnConflict" setter.
	ComponentUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ComponentUpsert) SetName(v string) *ComponentUpsert {
	u.Set(component.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateName() *ComponentUpsert {
	u.SetExcluded(component.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *ComponentUpsert) SetType(v component.Type) *ComponentUpsert {
	u.Set(component.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateType() *ComponentUpsert {
	u.SetExcluded(component.FieldType)
	return u
}

// SetConfig sets the "config" field.
func (u *ComponentUpsert) SetConfig(v map[string]string) *ComponentUpsert {
	u.Set(component.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateConfig() *ComponentUpsert {
	u.SetExcluded(component.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *ComponentUpsert) ClearConfig() *ComponentUpsert {
	u.SetNull(component.FieldConfig)
	return u
}

// SetDependsOn sets the "depends_on" field.
func (u *ComponentUpsert) SetDependsOn(v []uuid.UUID) *ComponentUpsert {
	u.Set(component.FieldDependsOn, v)
	return u
}

// UpdateDependsOn sets the "depends_on" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateDependsOn() *ComponentUpsert {
	u.SetExcluded(component.FieldDependsOn)
	return u
}

// ClearDependsOn clears the value of the "depends_on" field.
func (u *ComponentUpsert) ClearDependsOn() *ComponentUpsert {
	u.SetNull(component.FieldDependsOn)
	return u
}

// SetContinueOnFailure sets the "continue_on_failure" field.
func (u *ComponentUpsert) SetContinueOnFailure(v bool) *ComponentUpsert {
	u.Set(component.FieldContinueOnFailure, v)
	return u
}

// UpdateContinueOnFailure sets the "continue_on_failure" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateContinueOnFailure() *ComponentUpsert {
	u.SetExcluded(component.FieldContinueOnFailure)
	return u
}

// SetRequiresApproval sets the "requires_approval" field.
func (u *ComponentUpsert) SetRequiresApproval(v bool) *ComponentUpsert {
	u.Set(component.FieldRequiresApproval, v)
	return u
}

// UpdateRequiresApproval sets the "requires_approval" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateRequiresApproval() *ComponentUpsert {
	u.SetExcluded(component.FieldRequiresApproval)
	return u
}

// SetTargetClusterID sets the "target_cluster_id" field.
func (u *ComponentUpsert) SetTargetClusterID(v uuid.UUID) *ComponentUpsert {
	u.Set(component.FieldTargetClusterID, v)
	return u
}

// UpdateTargetClusterID sets the "target_cluster_id" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateTargetClusterID() *ComponentUpsert {
	u.SetExcluded(component.FieldTargetClusterID)
	return u
}

// ClearTargetClusterID clears the value of the "target_cluster_id" field.
func (u *ComponentUpsert) ClearTargetClusterID() *ComponentUpsert {
	u.SetNull(component.FieldTargetClusterID)
	return u
}

// SetTargetNamespace sets the "target_namespace" field.
func (u *ComponentUpsert) SetTargetNamespace(v string) *ComponentUpsert {
	u.Set(component.FieldTargetNamespace, v)
	return u
}

// UpdateTargetNamespace sets the "target_namespace" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateTargetNamespace() *ComponentUpsert {
	u.SetExcluded(component.FieldTargetNamespace)
	return u
}

// ClearTargetNamespace clears the value of the "target_namespace" field.
func (u *ComponentUpsert) ClearTargetNamespace() *ComponentUpsert {
	u.SetNull(component.FieldTargetNamespace)
	return u
}

// SetChartCredentialID sets the "chart_credential_id" field.
func (u *ComponentUpsert) SetChartCredentialID(v uuid.UUID) *ComponentUpsert {
	u.Set(component.FieldChartCredentialID, v)
	return u
}

// UpdateChartCredentialID sets the "chart_credential_id" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateChartCredentialID() *ComponentUpsert {
	u.SetExcluded(component.FieldChartCredentialID)
	return u
}

// ClearChartCredentialID clears the value of the "chart_credential_id" field.
func (u *ComponentUpsert) ClearChartCredentialID() *ComponentUpsert {
	u.SetNull(component.FieldChartCredentialID)
	return u
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (u *ComponentUpsert) SetGithubInstallationID(v uuid.UUID) *ComponentUpsert {
	u.Set(component.FieldGithubInstallationID, v)
	return u
}

// UpdateGithubInstallationID sets the "github_installation_id" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateGithubInstallationID() *ComponentUpsert {
	u.SetExcluded(component.FieldGithubInstallationID)
	return u
}

// ClearGithubInstallationID clears the value of the "github_installation_id" field.
func (u *ComponentUpsert) ClearGithubInstallationID() *ComponentUpsert {
	u.SetNull(component.FieldGithubInstallationID)
	return u
}

// SetPosition sets the "position" field.
func (u *ComponentUpsert) SetPosition(v map[string]float64) *ComponentUpsert {
	u.Set(component.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *ComponentUpsert) UpdatePosition() *ComponentUpsert {
	u.SetExcluded(component.FieldPosition)
	return u
}

// ClearPosition clears the value of the "position" field.
func (u *ComponentUpsert) ClearPosition() *ComponentUpsert {
	u.SetNull(component.FieldPosition)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ComponentUpsert) SetGroupID(v uuid.UUID) *ComponentUpsert {
	u.Set(component.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateGroupID() *ComponentUpsert {
	u.SetExcluded(component.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ComponentUpsert) ClearGroupID() *ComponentUpsert {
	u.SetNull(component.FieldGroupID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComponentUpsert) SetUpdatedAt(v time.Time) *ComponentUpsert {
	u.Set(component.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComponentUpsert) UpdateUpdatedAt() *ComponentUpsert {
	u.SetExcluded(component.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Component.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(component.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComponentUpsertOne) UpdateNewValues() *ComponentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(component.FieldID)
		}
		if _, exists := u.create.mutation.OrganizationID(); exists {
			s.SetIgnore(component.FieldOrganizationID)
		}
		if _, exists := u.create.mutation.ApplicationID(); exists {
			s.SetIgnore(component.FieldApplicationID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(component.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Component.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ComponentUpsertOne) Ignore() *ComponentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComponentUpsertOne) DoNothing() *ComponentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComponentCreate.OnConflict
// documentation for more info.
func (u *ComponentUpsertOne) Update(set func(*ComponentUpsert)) *ComponentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComponentUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ComponentUpsertOne) SetName(v string) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateName() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ComponentUpsertOne) SetType(v component.Type) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateType() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateType()
	})
}

// SetConfig sets the "config" field.
func (u *ComponentUpsertOne) SetConfig(v map[string]string) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateConfig() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *ComponentUpsertOne) ClearConfig() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearConfig()
	})
}

// SetDependsOn sets the "depends_on" field.
func (u *ComponentUpsertOne) SetDependsOn(v []uuid.UUID) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetDependsOn(v)
	})
}

// UpdateDependsOn sets the "depends_on" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateDependsOn() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateDependsOn()
	})
}

// ClearDependsOn clears the value of the "depends_on" field.
func (u *ComponentUpsertOne) ClearDependsOn() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearDependsOn()
	})
}

// SetContinueOnFailure sets the "continue_on_failure" field.
func (u *ComponentUpsertOne) SetContinueOnFailure(v bool) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetContinueOnFailure(v)
	})
}

// UpdateContinueOnFailure sets the "continue_on_failure" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateContinueOnFailure() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateContinueOnFailure()
	})
}

// SetRequiresApproval sets the "requires_approval" field.
func (u *ComponentUpsertOne) SetRequiresApproval(v bool) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetRequiresApproval(v)
	})
}

// UpdateRequiresApproval sets the "requires_approval" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateRequiresApproval() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateRequiresApproval()
	})
}

// SetTargetClusterID sets the "target_cluster_id" field.
func (u *ComponentUpsertOne) SetTargetClusterID(v uuid.UUID) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetTargetClusterID(v)
	})
}

// UpdateTargetClusterID sets the "target_cluster_id" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateTargetClusterID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateTargetClusterID()
	})
}

// ClearTargetClusterID clears the value of the "target_cluster_id" field.
func (u *ComponentUpsertOne) ClearTargetClusterID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearTargetClusterID()
	})
}

// SetTargetNamespace sets the "target_namespace" field.
func (u *ComponentUpsertOne) SetTargetNamespace(v string) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetTargetNamespace(v)
	})
}

// UpdateTargetNamespace sets the "target_namespace" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateTargetNamespace() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateTargetNamespace()
	})
}

// ClearTargetNamespace clears the value of the "target_namespace" field.
func (u *ComponentUpsertOne) ClearTargetNamespace() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearTargetNamespace()
	})
}

// SetChartCredentialID sets the "chart_credential_id" field.
func (u *ComponentUpsertOne) SetChartCredentialID(v uuid.UUID) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetChartCredentialID(v)
	})
}

// UpdateChartCredentialID sets the "chart_credential_id" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateChartCredentialID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateChartCredentialID()
	})
}

// ClearChartCredentialID clears the value of the "chart_credential_id" field.
func (u *ComponentUpsertOne) ClearChartCredentialID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearChartCredentialID()
	})
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (u *ComponentUpsertOne) SetGithubInstallationID(v uuid.UUID) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetGithubInstallationID(v)
	})
}

// UpdateGithubInstallationID sets the "github_installation_id" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateGithubInstallationID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateGithubInstallationID()
	})
}

// ClearGithubInstallationID clears the value of the "github_installation_id" field.
func (u *ComponentUpsertOne) ClearGithubInstallationID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearGithubInstallationID()
	})
}

// SetPosition sets the "position" field.
func (u *ComponentUpsertOne) SetPosition(v map[string]float64) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdatePosition() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdatePosition()
	})
}

// ClearPosition clears the value of the "position" field.
func (u *ComponentUpsertOne) ClearPosition() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearPosition()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ComponentUpsertOne) SetGroupID(v uuid.UUID) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateGroupID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ComponentUpsertOne) ClearGroupID() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearGroupID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComponentUpsertOne) SetUpdatedAt(v time.Time) *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComponentUpsertOne) UpdateUpdatedAt() *ComponentUpsertOne {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ComponentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComponentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComponentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ComponentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ComponentUpsertOne.ID is not supported by MySQL driver. Use ComponentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ComponentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ComponentCreateBulk is the builder for creating many Component entities in bulk.
type ComponentCreateBulk struct {
	config
	err      error
	builders []*ComponentCreate
	conflict []sql.ConflictOption
}

// Save creates the Component entities in the database.
func (_c *ComponentCreateBulk) Save(ctx context.Context) ([]*Component, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Component, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComponentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ComponentCreateBulk) SaveX(ctx context.Context) []*Component {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Component.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComponentUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComponentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ComponentUpsertBulk {
	_c.conflict = opts
	return &ComponentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Component.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComponentCreateBulk) OnConflictColumns(columns ...string) *ComponentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComponentUpsertBulk{
		create: _c,
	}
}

// ComponentUpsertBulk is the builder for "upsert"-ing
// a bulk of Component nodes.
type ComponentUpsertBulk struct {
	create *ComponentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Component.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(component.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComponentUpsertBulk) UpdateNewValues() *ComponentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(component.FieldID)
			}
			if _, exists := b.mutation.OrganizationID(); exists {
				s.SetIgnore(component.FieldOrganizationID)
			}
			if _, exists := b.mutation.ApplicationID(); exists {
				s.SetIgnore(component.FieldApplicationID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(component.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Component.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ComponentUpsertBulk) Ignore() *ComponentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComponentUpsertBulk) DoNothing() *ComponentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComponentCreateBulk.OnConflict
// documentation for more info.
func (u *ComponentUpsertBulk) Update(set func(*ComponentUpsert)) *ComponentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComponentUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ComponentUpsertBulk) SetName(v string) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateName() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *ComponentUpsertBulk) SetType(v component.Type) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateType() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateType()
	})
}

// SetConfig sets the "config" field.
func (u *ComponentUpsertBulk) SetConfig(v map[string]string) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateConfig() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *ComponentUpsertBulk) ClearConfig() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearConfig()
	})
}

// SetDependsOn sets the "depends_on" field.
func (u *ComponentUpsertBulk) SetDependsOn(v []uuid.UUID) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetDependsOn(v)
	})
}

// UpdateDependsOn sets the "depends_on" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateDependsOn() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateDependsOn()
	})
}

// ClearDependsOn clears the value of the "depends_on" field.
func (u *ComponentUpsertBulk) ClearDependsOn() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearDependsOn()
	})
}

// SetContinueOnFailure sets the "continue_on_failure" field.
func (u *ComponentUpsertBulk) SetContinueOnFailure(v bool) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetContinueOnFailure(v)
	})
}

// UpdateContinueOnFailure sets the "continue_on_failure" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateContinueOnFailure() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateContinueOnFailure()
	})
}

// SetRequiresApproval sets the "requires_approval" field.
func (u *ComponentUpsertBulk) SetRequiresApproval(v bool) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetRequiresApproval(v)
	})
}

// UpdateRequiresApproval sets the "requires_approval" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateRequiresApproval() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateRequiresApproval()
	})
}

// SetTargetClusterID sets the "target_cluster_id" field.
func (u *ComponentUpsertBulk) SetTargetClusterID(v uuid.UUID) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetTargetClusterID(v)
	})
}

// UpdateTargetClusterID sets the "target_cluster_id" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateTargetClusterID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateTargetClusterID()
	})
}

// ClearTargetClusterID clears the value of the "target_cluster_id" field.
func (u *ComponentUpsertBulk) ClearTargetClusterID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearTargetClusterID()
	})
}

// SetTargetNamespace sets the "target_namespace" field.
func (u *ComponentUpsertBulk) SetTargetNamespace(v string) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetTargetNamespace(v)
	})
}

// UpdateTargetNamespace sets the "target_namespace" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateTargetNamespace() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateTargetNamespace()
	})
}

// ClearTargetNamespace clears the value of the "target_namespace" field.
func (u *ComponentUpsertBulk) ClearTargetNamespace() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearTargetNamespace()
	})
}

// SetChartCredentialID sets the "chart_credential_id" field.
func (u *ComponentUpsertBulk) SetChartCredentialID(v uuid.UUID) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetChartCredentialID(v)
	})
}

// UpdateChartCredentialID sets the "chart_credential_id" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateChartCredentialID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateChartCredentialID()
	})
}

// ClearChartCredentialID clears the value of the "chart_credential_id" field.
func (u *ComponentUpsertBulk) ClearChartCredentialID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearChartCredentialID()
	})
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (u *ComponentUpsertBulk) SetGithubInstallationID(v uuid.UUID) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetGithubInstallationID(v)
	})
}

// UpdateGithubInstallationID sets the "github_installation_id" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateGithubInstallationID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateGithubInstallationID()
	})
}

// ClearGithubInstallationID clears the value of the "github_installation_id" field.
func (u *ComponentUpsertBulk) ClearGithubInstallationID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearGithubInstallationID()
	})
}

// SetPosition sets the "position" field.
func (u *ComponentUpsertBulk) SetPosition(v map[string]float64) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdatePosition() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdatePosition()
	})
}

// ClearPosition clears the value of the "position" field.
func (u *ComponentUpsertBulk) ClearPosition() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearPosition()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ComponentUpsertBulk) SetGroupID(v uuid.UUID) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateGroupID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ComponentUpsertBulk) ClearGroupID() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.ClearGroupID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComponentUpsertBulk) SetUpdatedAt(v time.Time) *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComponentUpsertBulk) UpdateUpdatedAt() *ComponentUpsertBulk {
	return u.Update(func(s *ComponentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ComponentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ComponentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComponentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComponentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
