// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/spacefleet/ent/deployment"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// DeploymentUpdate is the builder for updating Deployment entities.
type DeploymentUpdate struct {
	config
	hooks    []Hook
	mutation *DeploymentMutation
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdate) Where(ps ...predicate.Deployment) *DeploymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *DeploymentUpdate) SetAction(v deployment.Action) *DeploymentUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableAction(v *deployment.Action) *DeploymentUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentUpdate) SetStatus(v deployment.Status) *DeploymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableStatus(v *deployment.Status) *DeploymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeploymentUpdate) SetMessage(v string) *DeploymentUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableMessage(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *DeploymentUpdate) ClearMessage() *DeploymentUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *DeploymentUpdate) SetJobID(v string) *DeploymentUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableJobID(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// ClearJobID clears the value of the "job_id" field.
func (_u *DeploymentUpdate) ClearJobID() *DeploymentUpdate {
	_u.mutation.ClearJobID()
	return _u
}

// SetRunName sets the "run_name" field.
func (_u *DeploymentUpdate) SetRunName(v string) *DeploymentUpdate {
	_u.mutation.SetRunName(v)
	return _u
}

// SetNillableRunName sets the "run_name" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableRunName(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetRunName(*v)
	}
	return _u
}

// ClearRunName clears the value of the "run_name" field.
func (_u *DeploymentUpdate) ClearRunName() *DeploymentUpdate {
	_u.mutation.ClearRunName()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *DeploymentUpdate) SetLogs(v string) *DeploymentUpdate {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableLogs(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *DeploymentUpdate) ClearLogs() *DeploymentUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// SetChartRevision sets the "chart_revision" field.
func (_u *DeploymentUpdate) SetChartRevision(v string) *DeploymentUpdate {
	_u.mutation.SetChartRevision(v)
	return _u
}

// SetNillableChartRevision sets the "chart_revision" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableChartRevision(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetChartRevision(*v)
	}
	return _u
}

// ClearChartRevision clears the value of the "chart_revision" field.
func (_u *DeploymentUpdate) ClearChartRevision() *DeploymentUpdate {
	_u.mutation.ClearChartRevision()
	return _u
}

// SetValuesRevision sets the "values_revision" field.
func (_u *DeploymentUpdate) SetValuesRevision(v string) *DeploymentUpdate {
	_u.mutation.SetValuesRevision(v)
	return _u
}

// SetNillableValuesRevision sets the "values_revision" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableValuesRevision(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetValuesRevision(*v)
	}
	return _u
}

// ClearValuesRevision clears the value of the "values_revision" field.
func (_u *DeploymentUpdate) ClearValuesRevision() *DeploymentUpdate {
	_u.mutation.ClearValuesRevision()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeploymentUpdate) SetFinishedAt(v time.Time) *DeploymentUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableFinishedAt(v *time.Time) *DeploymentUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeploymentUpdate) ClearFinishedAt() *DeploymentUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeploymentUpdate) SetUpdatedAt(v time.Time) *DeploymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdate) Mutation() *DeploymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deployment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := deployment.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Deployment.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deployment.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.application"`)
	}
	return nil
}

func (_u *DeploymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(deployment.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deployment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(deployment.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(deployment.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(deployment.FieldJobID, field.TypeString, value)
	}
	if _u.mutation.JobIDCleared() {
		_spec.ClearField(deployment.FieldJobID, field.TypeString)
	}
	if value, ok := _u.mutation.RunName(); ok {
		_spec.SetField(deployment.FieldRunName, field.TypeString, value)
	}
	if _u.mutation.RunNameCleared() {
		_spec.ClearField(deployment.FieldRunName, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(deployment.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(deployment.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.ChartRevision(); ok {
		_spec.SetField(deployment.FieldChartRevision, field.TypeString, value)
	}
	if _u.mutation.ChartRevisionCleared() {
		_spec.ClearField(deployment.FieldChartRevision, field.TypeString)
	}
	if value, ok := _u.mutation.ValuesRevision(); ok {
		_spec.SetField(deployment.FieldValuesRevision, field.TypeString, value)
	}
	if _u.mutation.ValuesRevisionCleared() {
		_spec.ClearField(deployment.FieldValuesRevision, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deployment.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deployment.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deployment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentUpdateOne is the builder for updating a single Deployment entity.
type DeploymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeploymentMutation
}

// SetAction sets the "action" field.
func (_u *DeploymentUpdateOne) SetAction(v deployment.Action) *DeploymentUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableAction(v *deployment.Action) *DeploymentUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentUpdateOne) SetStatus(v deployment.Status) *DeploymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableStatus(v *deployment.Status) *DeploymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeploymentUpdateOne) SetMessage(v string) *DeploymentUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableMessage(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *DeploymentUpdateOne) ClearMessage() *DeploymentUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *DeploymentUpdateOne) SetJobID(v string) *DeploymentUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableJobID(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// ClearJobID clears the value of the "job_id" field.
func (_u *DeploymentUpdateOne) ClearJobID() *DeploymentUpdateOne {
	_u.mutation.ClearJobID()
	return _u
}

// SetRunName sets the "run_name" field.
func (_u *DeploymentUpdateOne) SetRunName(v string) *DeploymentUpdateOne {
	_u.mutation.SetRunName(v)
	return _u
}

// SetNillableRunName sets the "run_name" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableRunName(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetRunName(*v)
	}
	return _u
}

// ClearRunName clears the value of the "run_name" field.
func (_u *DeploymentUpdateOne) ClearRunName() *DeploymentUpdateOne {
	_u.mutation.ClearRunName()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *DeploymentUpdateOne) SetLogs(v string) *DeploymentUpdateOne {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableLogs(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *DeploymentUpdateOne) ClearLogs() *DeploymentUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// SetChartRevision sets the "chart_revision" field.
func (_u *DeploymentUpdateOne) SetChartRevision(v string) *DeploymentUpdateOne {
	_u.mutation.SetChartRevision(v)
	return _u
}

// SetNillableChartRevision sets the "chart_revision" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableChartRevision(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetChartRevision(*v)
	}
	return _u
}

// ClearChartRevision clears the value of the "chart_revision" field.
func (_u *DeploymentUpdateOne) ClearChartRevision() *DeploymentUpdateOne {
	_u.mutation.ClearChartRevision()
	return _u
}

// SetValuesRevision sets the "values_revision" field.
func (_u *DeploymentUpdateOne) SetValuesRevision(v string) *DeploymentUpdateOne {
	_u.mutation.SetValuesRevision(v)
	return _u
}

// SetNillableValuesRevision sets the "values_revision" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableValuesRevision(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetValuesRevision(*v)
	}
	return _u
}

// ClearValuesRevision clears the value of the "values_revision" field.
func (_u *DeploymentUpdateOne) ClearValuesRevision() *DeploymentUpdateOne {
	_u.mutation.ClearValuesRevision()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeploymentUpdateOne) SetFinishedAt(v time.Time) *DeploymentUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableFinishedAt(v *time.Time) *DeploymentUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeploymentUpdateOne) ClearFinishedAt() *DeploymentUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeploymentUpdateOne) SetUpdatedAt(v time.Time) *DeploymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdateOne) Mutation() *DeploymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdateOne) Where(ps ...predicate.Deployment) *DeploymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentUpdateOne) Select(field string, fields ...string) *DeploymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deployment entity.
func (_u *DeploymentUpdateOne) Save(ctx context.Context) (*Deployment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdateOne) SaveX(ctx context.Context) *Deployment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deployment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := deployment.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Deployment.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deployment.status": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.application"`)
	}
	return nil
}

func (_u *DeploymentUpdateOne) sqlSave(ctx context.Context) (_node *Deployment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deployment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.FieldID)
		for _, f := range fields {
			if !deployment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(deployment.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deployment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(deployment.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(deployment.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(deployment.FieldJobID, field.TypeString, value)
	}
	if _u.mutation.JobIDCleared() {
		_spec.ClearField(deployment.FieldJobID, field.TypeString)
	}
	if value, ok := _u.mutation.RunName(); ok {
		_spec.SetField(deployment.FieldRunName, field.TypeString, value)
	}
	if _u.mutation.RunNameCleared() {
		_spec.ClearField(deployment.FieldRunName, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(deployment.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(deployment.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.ChartRevision(); ok {
		_spec.SetField(deployment.FieldChartRevision, field.TypeString, value)
	}
	if _u.mutation.ChartRevisionCleared() {
		_spec.ClearField(deployment.FieldChartRevision, field.TypeString)
	}
	if value, ok := _u.mutation.ValuesRevision(); ok {
		_spec.SetField(deployment.FieldValuesRevision, field.TypeString, value)
	}
	if _u.mutation.ValuesRevisionCleared() {
		_spec.ClearField(deployment.FieldValuesRevision, field.TypeString)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deployment.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deployment.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deployment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Deployment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
