// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/application"
	"github.com/spacefleet/spacefleet/ent/deployment"
	"github.com/spacefleet/spacefleet/ent/organization"
)

// DeploymentCreate is the builder for creating a Deployment entity.
type DeploymentCreate struct {
	config
	mutation *DeploymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrganizationID sets the "organization_id" field.
func (_c *DeploymentCreate) SetOrganizationID(v uuid.UUID) *DeploymentCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetApplicationID sets the "application_id" field.
func (_c *DeploymentCreate) SetApplicationID(v uuid.UUID) *DeploymentCreate {
	_c.mutation.SetApplicationID(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *DeploymentCreate) SetAction(v deployment.Action) *DeploymentCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeploymentCreate) SetStatus(v deployment.Status) *DeploymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableStatus(v *deployment.Status) *DeploymentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *DeploymentCreate) SetMessage(v string) *DeploymentCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableMessage(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *DeploymentCreate) SetJobID(v string) *DeploymentCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableJobID(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetJobID(*v)
	}
	return _c
}

// SetRunName sets the "run_name" field.
func (_c *DeploymentCreate) SetRunName(v string) *DeploymentCreate {
	_c.mutation.SetRunName(v)
	return _c
}

// SetNillableRunName sets the "run_name" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableRunName(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetRunName(*v)
	}
	return _c
}

// SetLogs sets the "logs" field.
func (_c *DeploymentCreate) SetLogs(v string) *DeploymentCreate {
	_c.mutation.SetLogs(v)
	return _c
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableLogs(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetLogs(*v)
	}
	return _c
}

// SetChartRevision sets the "chart_revision" field.
func (_c *DeploymentCreate) SetChartRevision(v string) *DeploymentCreate {
	_c.mutation.SetChartRevision(v)
	return _c
}

// SetNillableChartRevision sets the "chart_revision" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableChartRevision(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetChartRevision(*v)
	}
	return _c
}

// SetValuesRevision sets the "values_revision" field.
func (_c *DeploymentCreate) SetValuesRevision(v string) *DeploymentCreate {
	_c.mutation.SetValuesRevision(v)
	return _c
}

// SetNillableValuesRevision sets the "values_revision" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableValuesRevision(v *string) *DeploymentCreate {
	if v != nil {
		_c.SetValuesRevision(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeploymentCreate) SetCreatedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableCreatedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *DeploymentCreate) SetFinishedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableFinishedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeploymentCreate) SetUpdatedAt(v time.Time) *DeploymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableUpdatedAt(v *time.Time) *DeploymentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeploymentCreate) SetID(v uuid.UUID) *DeploymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableID(v *uuid.UUID) *DeploymentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *DeploymentCreate) SetOrganization(v *Organization) *DeploymentCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetApplication sets the "application" edge to the Application entity.
func (_c *DeploymentCreate) SetApplication(v *Application) *DeploymentCreate {
	return _c.SetApplicationID(v.ID)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_c *DeploymentCreate) Mutation() *DeploymentMutation {
	return _c.mutation
}

// Save creates the Deployment in the database.
func (_c *DeploymentCreate) Save(ctx context.Context) (*Deployment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeploymentCreate) SaveX(ctx context.Context) *Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeploymentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := deployment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deployment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := deployment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := deployment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeploymentCreate) check() error {
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "Deployment.organization_id"`)}
	}
	if _, ok := _c.mutation.ApplicationID(); !ok {
		return &ValidationError{Name: "application_id", err: errors.New(`ent: missing required field "Deployment.application_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "Deployment.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := deployment.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Deployment.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Deployment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := deployment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Deployment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Deployment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Deployment.updated_at"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "Deployment.organization"`)}
	}
	if len(_c.mutation.ApplicationIDs()) == 0 {
		return &ValidationError{Name: "application", err: errors.New(`ent: missing required edge "Deployment.application"`)}
	}
	return nil
}

func (_c *DeploymentCreate) sqlSave(ctx context.Context) (*Deployment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeploymentCreate) createSpec() (*Deployment, *sqlgraph.CreateSpec) {
	var (
		_node = &Deployment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deployment.Table, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(deployment.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(deployment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(deployment.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(deployment.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.RunName(); ok {
		_spec.SetField(deployment.FieldRunName, field.TypeString, value)
		_node.RunName = value
	}
	if value, ok := _c.mutation.Logs(); ok {
		_spec.SetField(deployment.FieldLogs, field.TypeString, value)
		_node.Logs = value
	}
	if value, ok := _c.mutation.ChartRevision(); ok {
		_spec.SetField(deployment.FieldChartRevision, field.TypeString, value)
		_node.ChartRevision = value
	}
	if value, ok := _c.mutation.ValuesRevision(); ok {
		_spec.SetField(deployment.FieldValuesRevision, field.TypeString, value)
		_node.ValuesRevision = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deployment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(deployment.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(deployment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   deployment.OrganizationTable,
			Columns: []string{deployment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   deployment.ApplicationTable,
			Columns: []string{deployment.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deployment.Create().
//		SetOrganizationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeploymentCreate) OnConflict(opts ...sql.ConflictOption) *DeploymentUpsertOne {
	_c.conflict = opts
	return &DeploymentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeploymentCreate) OnConflictColumns(columns ...string) *DeploymentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeploymentUpsertOne{
		create: _c,
	}
}

type (
	// DeploymentUpsertOne is the builder for "upsert"-ing
	//  one Deployment node.
	DeploymentUpsertOne struct {
		create *DeploymentCreate
	}

	// DeploymentUpsert is the "OnConflict" setter.
	DeploymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetAction sets the "action" field.
func (u *DeploymentUpsert) SetAction(v deployment.Action) *DeploymentUpsert {
	u.Set(deployment.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateAction() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldAction)
	return u
}

// SetStatus sets the "status" field.
func (u *DeploymentUpsert) SetStatus(v deployment.Status) *DeploymentUpsert {
	u.Set(deployment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateStatus() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *DeploymentUpsert) SetMessage(v string) *DeploymentUpsert {
	u.Set(deployment.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateMessage() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *DeploymentUpsert) ClearMessage() *DeploymentUpsert {
	u.SetNull(deployment.FieldMessage)
	return u
}

// SetJobID sets the "job_id" field.
func (u *DeploymentUpsert) SetJobID(v string) *DeploymentUpsert {
	u.Set(deployment.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateJobID() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldJobID)
	return u
}

// ClearJobID clears the value of the "job_id" field.
func (u *DeploymentUpsert) ClearJobID() *DeploymentUpsert {
	u.SetNull(deployment.FieldJobID)
	return u
}

// SetRunName sets the "run_name" field.
func (u *DeploymentUpsert) SetRunName(v string) *DeploymentUpsert {
	u.Set(deployment.FieldRunName, v)
	return u
}

// UpdateRunName sets the "run_name" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateRunName() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldRunName)
	return u
}

// ClearRunName clears the value of the "run_name" field.
func (u *DeploymentUpsert) ClearRunName() *DeploymentUpsert {
	u.SetNull(deployment.FieldRunName)
	return u
}

// SetLogs sets the "logs" field.
func (u *DeploymentUpsert) SetLogs(v string) *DeploymentUpsert {
	u.Set(deployment.FieldLogs, v)
	return u
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateLogs() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldLogs)
	return u
}

// ClearLogs clears the value of the "logs" field.
func (u *DeploymentUpsert) ClearLogs() *DeploymentUpsert {
	u.SetNull(deployment.FieldLogs)
	return u
}

// SetChartRevision sets the "chart_revision" field.
func (u *DeploymentUpsert) SetChartRevision(v string) *DeploymentUpsert {
	u.Set(deployment.FieldChartRevision, v)
	return u
}

// UpdateChartRevision sets the "chart_revision" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateChartRevision() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldChartRevision)
	return u
}

// ClearChartRevision clears the value of the "chart_revision" field.
func (u *DeploymentUpsert) ClearChartRevision() *DeploymentUpsert {
	u.SetNull(deployment.FieldChartRevision)
	return u
}

// SetValuesRevision sets the "values_revision" field.
func (u *DeploymentUpsert) SetValuesRevision(v string) *DeploymentUpsert {
	u.Set(deployment.FieldValuesRevision, v)
	return u
}

// UpdateValuesRevision sets the "values_revision" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateValuesRevision() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldValuesRevision)
	return u
}

// ClearValuesRevision clears the value of the "values_revision" field.
func (u *DeploymentUpsert) ClearValuesRevision() *DeploymentUpsert {
	u.SetNull(deployment.FieldValuesRevision)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeploymentUpsert) SetFinishedAt(v time.Time) *DeploymentUpsert {
	u.Set(deployment.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateFinishedAt() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeploymentUpsert) ClearFinishedAt() *DeploymentUpsert {
	u.SetNull(deployment.FieldFinishedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentUpsert) SetUpdatedAt(v time.Time) *DeploymentUpsert {
	u.Set(deployment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateUpdatedAt() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentUpsertOne) UpdateNewValues() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deployment.FieldID)
		}
		if _, exists := u.create.mutation.OrganizationID(); exists {
			s.SetIgnore(deployment.FieldOrganizationID)
		}
		if _, exists := u.create.mutation.ApplicationID(); exists {
			s.SetIgnore(deployment.FieldApplicationID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(deployment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeploymentUpsertOne) Ignore() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentUpsertOne) DoNothing() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentCreate.OnConflict
// documentation for more info.
func (u *DeploymentUpsertOne) Update(set func(*DeploymentUpsert)) *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAction sets the "action" field.
func (u *DeploymentUpsertOne) SetAction(v deployment.Action) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateAction() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAction()
	})
}

// SetStatus sets the "status" field.
func (u *DeploymentUpsertOne) SetStatus(v deployment.Status) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateStatus() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *DeploymentUpsertOne) SetMessage(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateMessage() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *DeploymentUpsertOne) ClearMessage() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearMessage()
	})
}

// SetJobID sets the "job_id" field.
func (u *DeploymentUpsertOne) SetJobID(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateJobID() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateJobID()
	})
}

// ClearJobID clears the value of the "job_id" field.
func (u *DeploymentUpsertOne) ClearJobID() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearJobID()
	})
}

// SetRunName sets the "run_name" field.
func (u *DeploymentUpsertOne) SetRunName(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetRunName(v)
	})
}

// UpdateRunName sets the "run_name" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateRunName() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateRunName()
	})
}

// ClearRunName clears the value of the "run_name" field.
func (u *DeploymentUpsertOne) ClearRunName() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearRunName()
	})
}

// SetLogs sets the "logs" field.
func (u *DeploymentUpsertOne) SetLogs(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetLogs(v)
	})
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateLogs() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateLogs()
	})
}

// ClearLogs clears the value of the "logs" field.
func (u *DeploymentUpsertOne) ClearLogs() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearLogs()
	})
}

// SetChartRevision sets the "chart_revision" field.
func (u *DeploymentUpsertOne) SetChartRevision(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetChartRevision(v)
	})
}

// UpdateChartRevision sets the "chart_revision" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateChartRevision() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateChartRevision()
	})
}

// ClearChartRevision clears the value of the "chart_revision" field.
func (u *DeploymentUpsertOne) ClearChartRevision() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearChartRevision()
	})
}

// SetValuesRevision sets the "values_revision" field.
func (u *DeploymentUpsertOne) SetValuesRevision(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetValuesRevision(v)
	})
}

// UpdateValuesRevision sets the "values_revision" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateValuesRevision() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateValuesRevision()
	})
}

// ClearValuesRevision clears the value of the "values_revision" field.
func (u *DeploymentUpsertOne) ClearValuesRevision() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearValuesRevision()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeploymentUpsertOne) SetFinishedAt(v time.Time) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateFinishedAt() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeploymentUpsertOne) ClearFinishedAt() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentUpsertOne) SetUpdatedAt(v time.Time) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateUpdatedAt() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeploymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeploymentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeploymentUpsertOne.ID is not supported by MySQL driver. Use DeploymentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeploymentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeploymentCreateBulk is the builder for creating many Deployment entities in bulk.
type DeploymentCreateBulk struct {
	config
	err      error
	builders []*DeploymentCreate
	conflict []sql.ConflictOption
}

// Save creates the Deployment entities in the database.
func (_c *DeploymentCreateBulk) Save(ctx context.Context) ([]*Deployment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Deployment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeploymentCreateBulk) SaveX(ctx context.Context) []*Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deployment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentUpsert) {
//			SetOrganizationID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeploymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeploymentUpsertBulk {
	_c.conflict = opts
	return &DeploymentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeploymentCreateBulk) OnConflictColumns(columns ...string) *DeploymentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeploymentUpsertBulk{
		create: _c,
	}
}

// DeploymentUpsertBulk is the builder for "upsert"-ing
// a bulk of Deployment nodes.
type DeploymentUpsertBulk struct {
	create *DeploymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentUpsertBulk) UpdateNewValues() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deployment.FieldID)
			}
			if _, exists := b.mutation.OrganizationID(); exists {
				s.SetIgnore(deployment.FieldOrganizationID)
			}
			if _, exists := b.mutation.ApplicationID(); exists {
				s.SetIgnore(deployment.FieldApplicationID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(deployment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeploymentUpsertBulk) Ignore() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentUpsertBulk) DoNothing() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentCreateBulk.OnConflict
// documentation for more info.
func (u *DeploymentUpsertBulk) Update(set func(*DeploymentUpsert)) *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetAction sets the "action" field.
func (u *DeploymentUpsertBulk) SetAction(v deployment.Action) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateAction() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAction()
	})
}

// SetStatus sets the "status" field.
func (u *DeploymentUpsertBulk) SetStatus(v deployment.Status) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateStatus() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *DeploymentUpsertBulk) SetMessage(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateMessage() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *DeploymentUpsertBulk) ClearMessage() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearMessage()
	})
}

// SetJobID sets the "job_id" field.
func (u *DeploymentUpsertBulk) SetJobID(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateJobID() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateJobID()
	})
}

// ClearJobID clears the value of the "job_id" field.
func (u *DeploymentUpsertBulk) ClearJobID() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearJobID()
	})
}

// SetRunName sets the "run_name" field.
func (u *DeploymentUpsertBulk) SetRunName(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetRunName(v)
	})
}

// UpdateRunName sets the "run_name" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateRunName() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateRunName()
	})
}

// ClearRunName clears the value of the "run_name" field.
func (u *DeploymentUpsertBulk) ClearRunName() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearRunName()
	})
}

// SetLogs sets the "logs" field.
func (u *DeploymentUpsertBulk) SetLogs(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetLogs(v)
	})
}

// UpdateLogs sets the "logs" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateLogs() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateLogs()
	})
}

// ClearLogs clears the value of the "logs" field.
func (u *DeploymentUpsertBulk) ClearLogs() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearLogs()
	})
}

// SetChartRevision sets the "chart_revision" field.
func (u *DeploymentUpsertBulk) SetChartRevision(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetChartRevision(v)
	})
}

// UpdateChartRevision sets the "chart_revision" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateChartRevision() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateChartRevision()
	})
}

// ClearChartRevision clears the value of the "chart_revision" field.
func (u *DeploymentUpsertBulk) ClearChartRevision() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearChartRevision()
	})
}

// SetValuesRevision sets the "values_revision" field.
func (u *DeploymentUpsertBulk) SetValuesRevision(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetValuesRevision(v)
	})
}

// UpdateValuesRevision sets the "values_revision" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateValuesRevision() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateValuesRevision()
	})
}

// ClearValuesRevision clears the value of the "values_revision" field.
func (u *DeploymentUpsertBulk) ClearValuesRevision() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearValuesRevision()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *DeploymentUpsertBulk) SetFinishedAt(v time.Time) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateFinishedAt() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *DeploymentUpsertBulk) ClearFinishedAt() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearFinishedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeploymentUpsertBulk) SetUpdatedAt(v time.Time) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateUpdatedAt() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DeploymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeploymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
