// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/githubinstallation"
	"github.com/spacefleet/spacefleet/ent/organization"
)

// GitHubInstallation is the model entity for the GitHubInstallation schema.
type GitHubInstallation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// InstallationID holds the value of the "installation_id" field.
	InstallationID int64 `json:"installation_id,omitempty"`
	// AccountLogin holds the value of the "account_login" field.
	AccountLogin string `json:"account_login,omitempty"`
	// AccountType holds the value of the "account_type" field.
	AccountType string `json:"account_type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GitHubInstallationQuery when eager-loading is set.
	Edges        GitHubInstallationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GitHubInstallationEdges holds the relations/edges for other nodes in the graph.
type GitHubInstallationEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GitHubInstallationEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GitHubInstallation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case githubinstallation.FieldInstallationID:
			values[i] = new(sql.NullInt64)
		case githubinstallation.FieldAccountLogin, githubinstallation.FieldAccountType:
			values[i] = new(sql.NullString)
		case githubinstallation.FieldCreatedAt, githubinstallation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case githubinstallation.FieldID, githubinstallation.FieldOrganizationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GitHubInstallation fields.
func (_m *GitHubInstallation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case githubinstallation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case githubinstallation.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				_m.OrganizationID = *value
			}
		case githubinstallation.FieldInstallationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field installation_id", values[i])
			} else if value.Valid {
				_m.InstallationID = value.Int64
			}
		case githubinstallation.FieldAccountLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_login", values[i])
			} else if value.Valid {
				_m.AccountLogin = value.String
			}
		case githubinstallation.FieldAccountType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_type", values[i])
			} else if value.Valid {
				_m.AccountType = value.String
			}
		case githubinstallation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case githubinstallation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GitHubInstallation.
// This includes values selected through modifiers, order, etc.
func (_m *GitHubInstallation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the GitHubInstallation entity.
func (_m *GitHubInstallation) QueryOrganization() *OrganizationQuery {
	return NewGitHubInstallationClient(_m.config).QueryOrganization(_m)
}

// Update returns a builder for updating this GitHubInstallation.
// Note that you need to call GitHubInstallation.Unwrap() before calling this method if this GitHubInstallation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GitHubInstallation) Update() *GitHubInstallationUpdateOne {
	return NewGitHubInstallationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GitHubInstallation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GitHubInstallation) Unwrap() *GitHubInstallation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GitHubInstallation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GitHubInstallation) String() string {
	var builder strings.Builder
	builder.WriteString("GitHubInstallation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("installation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InstallationID))
	builder.WriteString(", ")
	builder.WriteString("account_login=")
	builder.WriteString(_m.AccountLogin)
	builder.WriteString(", ")
	builder.WriteString("account_type=")
	builder.WriteString(_m.AccountType)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GitHubInstallations is a parsable slice of GitHubInstallation.
type GitHubInstallations []*GitHubInstallation
