// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/application"
	"github.com/spacefleet/spacefleet/ent/notificationchannel"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// NotificationChannelUpdate is the builder for updating NotificationChannel entities.
type NotificationChannelUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdate) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdate) SetName(v string) *NotificationChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableName(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *NotificationChannelUpdate) SetAddress(v string) *NotificationChannelUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableAddress(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetEncryptedTarget sets the "encrypted_target" field.
func (_u *NotificationChannelUpdate) SetEncryptedTarget(v []byte) *NotificationChannelUpdate {
	_u.mutation.SetEncryptedTarget(v)
	return _u
}

// ClearEncryptedTarget clears the value of the "encrypted_target" field.
func (_u *NotificationChannelUpdate) ClearEncryptedTarget() *NotificationChannelUpdate {
	_u.mutation.ClearEncryptedTarget()
	return _u
}

// SetEvents sets the "events" field.
func (_u *NotificationChannelUpdate) SetEvents(v []string) *NotificationChannelUpdate {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *NotificationChannelUpdate) AppendEvents(v []string) *NotificationChannelUpdate {
	_u.mutation.AppendEvents(v)
	return _u
}

// ClearEvents clears the value of the "events" field.
func (_u *NotificationChannelUpdate) ClearEvents() *NotificationChannelUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// SetApplicationID sets the "application_id" field.
func (_u *NotificationChannelUpdate) SetApplicationID(v uuid.UUID) *NotificationChannelUpdate {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableApplicationID(v *uuid.UUID) *NotificationChannelUpdate {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// ClearApplicationID clears the value of the "application_id" field.
func (_u *NotificationChannelUpdate) ClearApplicationID() *NotificationChannelUpdate {
	_u.mutation.ClearApplicationID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdate) SetUpdatedAt(v time.Time) *NotificationChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *NotificationChannelUpdate) SetApplication(v *Application) *NotificationChannelUpdate {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdate) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *NotificationChannelUpdate) ClearApplication() *NotificationChannelUpdate {
	_u.mutation.ClearApplication()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannel.organization"`)
	}
	return nil
}

func (_u *NotificationChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(notificationchannel.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedTarget(); ok {
		_spec.SetField(notificationchannel.FieldEncryptedTarget, field.TypeBytes, value)
	}
	if _u.mutation.EncryptedTargetCleared() {
		_spec.ClearField(notificationchannel.FieldEncryptedTarget, field.TypeBytes)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(notificationchannel.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationchannel.FieldEvents, value)
		})
	}
	if _u.mutation.EventsCleared() {
		_spec.ClearField(notificationchannel.FieldEvents, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationchannel.ApplicationTable,
			Columns: []string{notificationchannel.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationchannel.ApplicationTable,
			Columns: []string{notificationchannel.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationChannelUpdateOne is the builder for updating a single NotificationChannel entity.
type NotificationChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdateOne) SetName(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableName(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *NotificationChannelUpdateOne) SetAddress(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableAddress(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetEncryptedTarget sets the "encrypted_target" field.
func (_u *NotificationChannelUpdateOne) SetEncryptedTarget(v []byte) *NotificationChannelUpdateOne {
	_u.mutation.SetEncryptedTarget(v)
	return _u
}

// ClearEncryptedTarget clears the value of the "encrypted_target" field.
func (_u *NotificationChannelUpdateOne) ClearEncryptedTarget() *NotificationChannelUpdateOne {
	_u.mutation.ClearEncryptedTarget()
	return _u
}

// SetEvents sets the "events" field.
func (_u *NotificationChannelUpdateOne) SetEvents(v []string) *NotificationChannelUpdateOne {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *NotificationChannelUpdateOne) AppendEvents(v []string) *NotificationChannelUpdateOne {
	_u.mutation.AppendEvents(v)
	return _u
}

// ClearEvents clears the value of the "events" field.
func (_u *NotificationChannelUpdateOne) ClearEvents() *NotificationChannelUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// SetApplicationID sets the "application_id" field.
func (_u *NotificationChannelUpdateOne) SetApplicationID(v uuid.UUID) *NotificationChannelUpdateOne {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableApplicationID(v *uuid.UUID) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// ClearApplicationID clears the value of the "application_id" field.
func (_u *NotificationChannelUpdateOne) ClearApplicationID() *NotificationChannelUpdateOne {
	_u.mutation.ClearApplicationID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdateOne) SetUpdatedAt(v time.Time) *NotificationChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *NotificationChannelUpdateOne) SetApplication(v *Application) *NotificationChannelUpdateOne {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdateOne) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *NotificationChannelUpdateOne) ClearApplication() *NotificationChannelUpdateOne {
	_u.mutation.ClearApplication()
	return _u
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdateOne) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationChannelUpdateOne) Select(field string, fields ...string) *NotificationChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationChannel entity.
func (_u *NotificationChannelUpdateOne) Save(ctx context.Context) (*NotificationChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) SaveX(ctx context.Context) *NotificationChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannel.organization"`)
	}
	return nil
}

func (_u *NotificationChannelUpdateOne) sqlSave(ctx context.Context) (_node *NotificationChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannel.FieldID)
		for _, f := range fields {
			if !notificationchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(notificationchannel.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedTarget(); ok {
		_spec.SetField(notificationchannel.FieldEncryptedTarget, field.TypeBytes, value)
	}
	if _u.mutation.EncryptedTargetCleared() {
		_spec.ClearField(notificationchannel.FieldEncryptedTarget, field.TypeBytes)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(notificationchannel.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notificationchannel.FieldEvents, value)
		})
	}
	if _u.mutation.EventsCleared() {
		_spec.ClearField(notificationchannel.FieldEvents, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationchannel.ApplicationTable,
			Columns: []string{notificationchannel.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   notificationchannel.ApplicationTable,
			Columns: []string{notificationchannel.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
