// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/application"
	"github.com/spacefleet/spacefleet/ent/planpolicy"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// PlanPolicyUpdate is the builder for updating PlanPolicy entities.
type PlanPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *PlanPolicyMutation
}

// Where appends a list predicates to the PlanPolicyUpdate builder.
func (_u *PlanPolicyUpdate) Where(ps ...predicate.PlanPolicy) *PlanPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PlanPolicyUpdate) SetName(v string) *PlanPolicyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableName(v *string) *PlanPolicyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanPolicyUpdate) SetDescription(v string) *PlanPolicyUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableDescription(v *string) *PlanPolicyUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanPolicyUpdate) ClearDescription() *PlanPolicyUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRego sets the "rego" field.
func (_u *PlanPolicyUpdate) SetRego(v string) *PlanPolicyUpdate {
	_u.mutation.SetRego(v)
	return _u
}

// SetNillableRego sets the "rego" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableRego(v *string) *PlanPolicyUpdate {
	if v != nil {
		_u.SetRego(*v)
	}
	return _u
}

// SetEnforcement sets the "enforcement" field.
func (_u *PlanPolicyUpdate) SetEnforcement(v planpolicy.Enforcement) *PlanPolicyUpdate {
	_u.mutation.SetEnforcement(v)
	return _u
}

// SetNillableEnforcement sets the "enforcement" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableEnforcement(v *planpolicy.Enforcement) *PlanPolicyUpdate {
	if v != nil {
		_u.SetEnforcement(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PlanPolicyUpdate) SetEnabled(v bool) *PlanPolicyUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableEnabled(v *bool) *PlanPolicyUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetApplicationID sets the "application_id" field.
func (_u *PlanPolicyUpdate) SetApplicationID(v uuid.UUID) *PlanPolicyUpdate {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *PlanPolicyUpdate) SetNillableApplicationID(v *uuid.UUID) *PlanPolicyUpdate {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// ClearApplicationID clears the value of the "application_id" field.
func (_u *PlanPolicyUpdate) ClearApplicationID() *PlanPolicyUpdate {
	_u.mutation.ClearApplicationID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanPolicyUpdate) SetUpdatedAt(v time.Time) *PlanPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *PlanPolicyUpdate) SetApplication(v *Application) *PlanPolicyUpdate {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the PlanPolicyMutation object of the builder.
func (_u *PlanPolicyUpdate) Mutation() *PlanPolicyMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *PlanPolicyUpdate) ClearApplication() *PlanPolicyUpdate {
	_u.mutation.ClearApplication()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := planpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanPolicyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := planpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlanPolicy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Enforcement(); ok {
		if err := planpolicy.EnforcementValidator(v); err != nil {
			return &ValidationError{Name: "enforcement", err: fmt.Errorf(`ent: validator failed for field "PlanPolicy.enforcement": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlanPolicy.organization"`)
	}
	return nil
}

func (_u *PlanPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(planpolicy.Table, planpolicy.Columns, sqlgraph.NewFieldSpec(planpolicy.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(planpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(planpolicy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(planpolicy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Rego(); ok {
		_spec.SetField(planpolicy.FieldRego, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enforcement(); ok {
		_spec.SetField(planpolicy.FieldEnforcement, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(planpolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(planpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   planpolicy.ApplicationTable,
			Columns: []string{planpolicy.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   planpolicy.ApplicationTable,
			Columns: []string{planpolicy.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{planpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanPolicyUpdateOne is the builder for updating a single PlanPolicy entity.
type PlanPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanPolicyMutation
}

// SetName sets the "name" field.
func (_u *PlanPolicyUpdateOne) SetName(v string) *PlanPolicyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableName(v *string) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanPolicyUpdateOne) SetDescription(v string) *PlanPolicyUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableDescription(v *string) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanPolicyUpdateOne) ClearDescription() *PlanPolicyUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRego sets the "rego" field.
func (_u *PlanPolicyUpdateOne) SetRego(v string) *PlanPolicyUpdateOne {
	_u.mutation.SetRego(v)
	return _u
}

// SetNillableRego sets the "rego" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableRego(v *string) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetRego(*v)
	}
	return _u
}

// SetEnforcement sets the "enforcement" field.
func (_u *PlanPolicyUpdateOne) SetEnforcement(v planpolicy.Enforcement) *PlanPolicyUpdateOne {
	_u.mutation.SetEnforcement(v)
	return _u
}

// SetNillableEnforcement sets the "enforcement" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableEnforcement(v *planpolicy.Enforcement) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetEnforcement(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PlanPolicyUpdateOne) SetEnabled(v bool) *PlanPolicyUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableEnabled(v *bool) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetApplicationID sets the "application_id" field.
func (_u *PlanPolicyUpdateOne) SetApplicationID(v uuid.UUID) *PlanPolicyUpdateOne {
	_u.mutation.SetApplicationID(v)
	return _u
}

// SetNillableApplicationID sets the "application_id" field if the given value is not nil.
func (_u *PlanPolicyUpdateOne) SetNillableApplicationID(v *uuid.UUID) *PlanPolicyUpdateOne {
	if v != nil {
		_u.SetApplicationID(*v)
	}
	return _u
}

// ClearApplicationID clears the value of the "application_id" field.
func (_u *PlanPolicyUpdateOne) ClearApplicationID() *PlanPolicyUpdateOne {
	_u.mutation.ClearApplicationID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlanPolicyUpdateOne) SetUpdatedAt(v time.Time) *PlanPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetApplication sets the "application" edge to the Application entity.
func (_u *PlanPolicyUpdateOne) SetApplication(v *Application) *PlanPolicyUpdateOne {
	return _u.SetApplicationID(v.ID)
}

// Mutation returns the PlanPolicyMutation object of the builder.
func (_u *PlanPolicyUpdateOne) Mutation() *PlanPolicyMutation {
	return _u.mutation
}

// ClearApplication clears the "application" edge to the Application entity.
func (_u *PlanPolicyUpdateOne) ClearApplication() *PlanPolicyUpdateOne {
	_u.mutation.ClearApplication()
	return _u
}

// Where appends a list predicates to the PlanPolicyUpdate builder.
func (_u *PlanPolicyUpdateOne) Where(ps ...predicate.PlanPolicy) *PlanPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanPolicyUpdateOne) Select(field string, fields ...string) *PlanPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlanPolicy entity.
func (_u *PlanPolicyUpdateOne) Save(ctx context.Context) (*PlanPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanPolicyUpdateOne) SaveX(ctx context.Context) *PlanPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlanPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := planpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := planpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PlanPolicy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Enforcement(); ok {
		if err := planpolicy.EnforcementValidator(v); err != nil {
			return &ValidationError{Name: "enforcement", err: fmt.Errorf(`ent: validator failed for field "PlanPolicy.enforcement": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlanPolicy.organization"`)
	}
	return nil
}

func (_u *PlanPolicyUpdateOne) sqlSave(ctx context.Context) (_node *PlanPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(planpolicy.Table, planpolicy.Columns, sqlgraph.NewFieldSpec(planpolicy.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlanPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, planpolicy.FieldID)
		for _, f := range fields {
			if !planpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != planpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(planpolicy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(planpolicy.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(planpolicy.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Rego(); ok {
		_spec.SetField(planpolicy.FieldRego, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enforcement(); ok {
		_spec.SetField(planpolicy.FieldEnforcement, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(planpolicy.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(planpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ApplicationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   planpolicy.ApplicationTable,
			Columns: []string{planpolicy.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApplicationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   planpolicy.ApplicationTable,
			Columns: []string{planpolicy.ApplicationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(application.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlanPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{planpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
