// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/application"
	"github.com/spacefleet/spacefleet/ent/chartcredential"
	"github.com/spacefleet/spacefleet/ent/cluster"
	"github.com/spacefleet/spacefleet/ent/component"
	"github.com/spacefleet/spacefleet/ent/componentgroup"
	"github.com/spacefleet/spacefleet/ent/componentrun"
	"github.com/spacefleet/spacefleet/ent/githubinstallation"
	"github.com/spacefleet/spacefleet/ent/invitation"
	"github.com/spacefleet/spacefleet/ent/membership"
	"github.com/spacefleet/spacefleet/ent/organization"
	"github.com/spacefleet/spacefleet/ent/schema"
	"github.com/spacefleet/spacefleet/ent/tektoninstallation"
	"github.com/spacefleet/spacefleet/ent/user"
	"github.com/spacefleet/spacefleet/ent/workflowrun"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	applicationFields := schema.Application{}.Fields()
	_ = applicationFields
	// applicationDescName is the schema descriptor for name field.
	applicationDescName := applicationFields[2].Descriptor()
	// application.NameValidator is a validator for the "name" field. It is called by the builders before save.
	application.NameValidator = applicationDescName.Validators[0].(func(string) error)
	// applicationDescImported is the schema descriptor for imported field.
	applicationDescImported := applicationFields[3].Descriptor()
	// application.DefaultImported holds the default value on creation for the imported field.
	application.DefaultImported = applicationDescImported.Default.(bool)
	// applicationDescTargetNamespace is the schema descriptor for target_namespace field.
	applicationDescTargetNamespace := applicationFields[4].Descriptor()
	// application.TargetNamespaceValidator is a validator for the "target_namespace" field. It is called by the builders before save.
	application.TargetNamespaceValidator = applicationDescTargetNamespace.Validators[0].(func(string) error)
	// applicationDescCreatedAt is the schema descriptor for created_at field.
	applicationDescCreatedAt := applicationFields[7].Descriptor()
	// application.DefaultCreatedAt holds the default value on creation for the created_at field.
	application.DefaultCreatedAt = applicationDescCreatedAt.Default.(func() time.Time)
	// applicationDescUpdatedAt is the schema descriptor for updated_at field.
	applicationDescUpdatedAt := applicationFields[8].Descriptor()
	// application.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	application.DefaultUpdatedAt = applicationDescUpdatedAt.Default.(func() time.Time)
	// application.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	application.UpdateDefaultUpdatedAt = applicationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// applicationDescID is the schema descriptor for id field.
	applicationDescID := applicationFields[0].Descriptor()
	// application.DefaultID holds the default value on creation for the id field.
	application.DefaultID = applicationDescID.Default.(func() uuid.UUID)
	chartcredentialFields := schema.ChartCredential{}.Fields()
	_ = chartcredentialFields
	// chartcredentialDescName is the schema descriptor for name field.
	chartcredentialDescName := chartcredentialFields[2].Descriptor()
	// chartcredential.NameValidator is a validator for the "name" field. It is called by the builders before save.
	chartcredential.NameValidator = chartcredentialDescName.Validators[0].(func(string) error)
	// chartcredentialDescCreatedAt is the schema descriptor for created_at field.
	chartcredentialDescCreatedAt := chartcredentialFields[5].Descriptor()
	// chartcredential.DefaultCreatedAt holds the default value on creation for the created_at field.
	chartcredential.DefaultCreatedAt = chartcredentialDescCreatedAt.Default.(func() time.Time)
	// chartcredentialDescUpdatedAt is the schema descriptor for updated_at field.
	chartcredentialDescUpdatedAt := chartcredentialFields[6].Descriptor()
	// chartcredential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chartcredential.DefaultUpdatedAt = chartcredentialDescUpdatedAt.Default.(func() time.Time)
	// chartcredential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chartcredential.UpdateDefaultUpdatedAt = chartcredentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	// chartcredentialDescID is the schema descriptor for id field.
	chartcredentialDescID := chartcredentialFields[0].Descriptor()
	// chartcredential.DefaultID holds the default value on creation for the id field.
	chartcredential.DefaultID = chartcredentialDescID.Default.(func() uuid.UUID)
	clusterFields := schema.Cluster{}.Fields()
	_ = clusterFields
	// clusterDescName is the schema descriptor for name field.
	clusterDescName := clusterFields[2].Descriptor()
	// cluster.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cluster.NameValidator = clusterDescName.Validators[0].(func(string) error)
	// clusterDescCreatedAt is the schema descriptor for created_at field.
	clusterDescCreatedAt := clusterFields[11].Descriptor()
	// cluster.DefaultCreatedAt holds the default value on creation for the created_at field.
	cluster.DefaultCreatedAt = clusterDescCreatedAt.Default.(func() time.Time)
	// clusterDescUpdatedAt is the schema descriptor for updated_at field.
	clusterDescUpdatedAt := clusterFields[12].Descriptor()
	// cluster.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cluster.DefaultUpdatedAt = clusterDescUpdatedAt.Default.(func() time.Time)
	// cluster.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cluster.UpdateDefaultUpdatedAt = clusterDescUpdatedAt.UpdateDefault.(func() time.Time)
	// clusterDescID is the schema descriptor for id field.
	clusterDescID := clusterFields[0].Descriptor()
	// cluster.DefaultID holds the default value on creation for the id field.
	cluster.DefaultID = clusterDescID.Default.(func() uuid.UUID)
	componentFields := schema.Component{}.Fields()
	_ = componentFields
	// componentDescName is the schema descriptor for name field.
	componentDescName := componentFields[3].Descriptor()
	// component.NameValidator is a validator for the "name" field. It is called by the builders before save.
	component.NameValidator = componentDescName.Validators[0].(func(string) error)
	// componentDescContinueOnFailure is the schema descriptor for continue_on_failure field.
	componentDescContinueOnFailure := componentFields[7].Descriptor()
	// component.DefaultContinueOnFailure holds the default value on creation for the continue_on_failure field.
	component.DefaultContinueOnFailure = componentDescContinueOnFailure.Default.(bool)
	// componentDescRequiresApproval is the schema descriptor for requires_approval field.
	componentDescRequiresApproval := componentFields[8].Descriptor()
	// component.DefaultRequiresApproval holds the default value on creation for the requires_approval field.
	component.DefaultRequiresApproval = componentDescRequiresApproval.Default.(bool)
	// componentDescCreatedAt is the schema descriptor for created_at field.
	componentDescCreatedAt := componentFields[15].Descriptor()
	// component.DefaultCreatedAt holds the default value on creation for the created_at field.
	component.DefaultCreatedAt = componentDescCreatedAt.Default.(func() time.Time)
	// componentDescUpdatedAt is the schema descriptor for updated_at field.
	componentDescUpdatedAt := componentFields[16].Descriptor()
	// component.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	component.DefaultUpdatedAt = componentDescUpdatedAt.Default.(func() time.Time)
	// component.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	component.UpdateDefaultUpdatedAt = componentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// componentDescID is the schema descriptor for id field.
	componentDescID := componentFields[0].Descriptor()
	// component.DefaultID holds the default value on creation for the id field.
	component.DefaultID = componentDescID.Default.(func() uuid.UUID)
	componentgroupFields := schema.ComponentGroup{}.Fields()
	_ = componentgroupFields
	// componentgroupDescName is the schema descriptor for name field.
	componentgroupDescName := componentgroupFields[3].Descriptor()
	// componentgroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	componentgroup.NameValidator = componentgroupDescName.Validators[0].(func(string) error)
	// componentgroupDescCreatedAt is the schema descriptor for created_at field.
	componentgroupDescCreatedAt := componentgroupFields[7].Descriptor()
	// componentgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	componentgroup.DefaultCreatedAt = componentgroupDescCreatedAt.Default.(func() time.Time)
	// componentgroupDescUpdatedAt is the schema descriptor for updated_at field.
	componentgroupDescUpdatedAt := componentgroupFields[8].Descriptor()
	// componentgroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	componentgroup.DefaultUpdatedAt = componentgroupDescUpdatedAt.Default.(func() time.Time)
	// componentgroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	componentgroup.UpdateDefaultUpdatedAt = componentgroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// componentgroupDescID is the schema descriptor for id field.
	componentgroupDescID := componentgroupFields[0].Descriptor()
	// componentgroup.DefaultID holds the default value on creation for the id field.
	componentgroup.DefaultID = componentgroupDescID.Default.(func() uuid.UUID)
	componentrunFields := schema.ComponentRun{}.Fields()
	_ = componentrunFields
	// componentrunDescApprovedBy is the schema descriptor for approved_by field.
	componentrunDescApprovedBy := componentrunFields[10].Descriptor()
	// componentrun.DefaultApprovedBy holds the default value on creation for the approved_by field.
	componentrun.DefaultApprovedBy = componentrunDescApprovedBy.Default.(string)
	// componentrunDescCreatedAt is the schema descriptor for created_at field.
	componentrunDescCreatedAt := componentrunFields[14].Descriptor()
	// componentrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	componentrun.DefaultCreatedAt = componentrunDescCreatedAt.Default.(func() time.Time)
	// componentrunDescUpdatedAt is the schema descriptor for updated_at field.
	componentrunDescUpdatedAt := componentrunFields[17].Descriptor()
	// componentrun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	componentrun.DefaultUpdatedAt = componentrunDescUpdatedAt.Default.(func() time.Time)
	// componentrun.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	componentrun.UpdateDefaultUpdatedAt = componentrunDescUpdatedAt.UpdateDefault.(func() time.Time)
	// componentrunDescID is the schema descriptor for id field.
	componentrunDescID := componentrunFields[0].Descriptor()
	// componentrun.DefaultID holds the default value on creation for the id field.
	componentrun.DefaultID = componentrunDescID.Default.(func() uuid.UUID)
	githubinstallationFields := schema.GitHubInstallation{}.Fields()
	_ = githubinstallationFields
	// githubinstallationDescCreatedAt is the schema descriptor for created_at field.
	githubinstallationDescCreatedAt := githubinstallationFields[5].Descriptor()
	// githubinstallation.DefaultCreatedAt holds the default value on creation for the created_at field.
	githubinstallation.DefaultCreatedAt = githubinstallationDescCreatedAt.Default.(func() time.Time)
	// githubinstallationDescUpdatedAt is the schema descriptor for updated_at field.
	githubinstallationDescUpdatedAt := githubinstallationFields[6].Descriptor()
	// githubinstallation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	githubinstallation.DefaultUpdatedAt = githubinstallationDescUpdatedAt.Default.(func() time.Time)
	// githubinstallation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	githubinstallation.UpdateDefaultUpdatedAt = githubinstallationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// githubinstallationDescID is the schema descriptor for id field.
	githubinstallationDescID := githubinstallationFields[0].Descriptor()
	// githubinstallation.DefaultID holds the default value on creation for the id field.
	githubinstallation.DefaultID = githubinstallationDescID.Default.(func() uuid.UUID)
	invitationFields := schema.Invitation{}.Fields()
	_ = invitationFields
	// invitationDescEmail is the schema descriptor for email field.
	invitationDescEmail := invitationFields[2].Descriptor()
	// invitation.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	invitation.EmailValidator = invitationDescEmail.Validators[0].(func(string) error)
	// invitationDescCreatedAt is the schema descriptor for created_at field.
	invitationDescCreatedAt := invitationFields[9].Descriptor()
	// invitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	invitation.DefaultCreatedAt = invitationDescCreatedAt.Default.(func() time.Time)
	// invitationDescID is the schema descriptor for id field.
	invitationDescID := invitationFields[0].Descriptor()
	// invitation.DefaultID holds the default value on creation for the id field.
	invitation.DefaultID = invitationDescID.Default.(func() uuid.UUID)
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipFields[4].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipFields[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescName is the schema descriptor for name field.
	organizationDescName := organizationFields[1].Descriptor()
	// organization.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organization.NameValidator = organizationDescName.Validators[0].(func(string) error)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[2].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescUpdatedAt is the schema descriptor for updated_at field.
	organizationDescUpdatedAt := organizationFields[3].Descriptor()
	// organization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organization.DefaultUpdatedAt = organizationDescUpdatedAt.Default.(func() time.Time)
	// organization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organization.UpdateDefaultUpdatedAt = organizationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	tektoninstallationFields := schema.TektonInstallation{}.Fields()
	_ = tektoninstallationFields
	// tektoninstallationDescEnabled is the schema descriptor for enabled field.
	tektoninstallationDescEnabled := tektoninstallationFields[2].Descriptor()
	// tektoninstallation.DefaultEnabled holds the default value on creation for the enabled field.
	tektoninstallation.DefaultEnabled = tektoninstallationDescEnabled.Default.(bool)
	// tektoninstallationDescCreatedAt is the schema descriptor for created_at field.
	tektoninstallationDescCreatedAt := tektoninstallationFields[8].Descriptor()
	// tektoninstallation.DefaultCreatedAt holds the default value on creation for the created_at field.
	tektoninstallation.DefaultCreatedAt = tektoninstallationDescCreatedAt.Default.(func() time.Time)
	// tektoninstallationDescUpdatedAt is the schema descriptor for updated_at field.
	tektoninstallationDescUpdatedAt := tektoninstallationFields[9].Descriptor()
	// tektoninstallation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tektoninstallation.DefaultUpdatedAt = tektoninstallationDescUpdatedAt.Default.(func() time.Time)
	// tektoninstallation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tektoninstallation.UpdateDefaultUpdatedAt = tektoninstallationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tektoninstallationDescID is the schema descriptor for id field.
	tektoninstallationDescID := tektoninstallationFields[0].Descriptor()
	// tektoninstallation.DefaultID holds the default value on creation for the id field.
	tektoninstallation.DefaultID = tektoninstallationDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescOidcSubject is the schema descriptor for oidc_subject field.
	userDescOidcSubject := userFields[1].Descriptor()
	// user.OidcSubjectValidator is a validator for the "oidc_subject" field. It is called by the builders before save.
	user.OidcSubjectValidator = userDescOidcSubject.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	workflowrunFields := schema.WorkflowRun{}.Fields()
	_ = workflowrunFields
	// workflowrunDescCreatedAt is the schema descriptor for created_at field.
	workflowrunDescCreatedAt := workflowrunFields[8].Descriptor()
	// workflowrun.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflowrun.DefaultCreatedAt = workflowrunDescCreatedAt.Default.(func() time.Time)
	// workflowrunDescUpdatedAt is the schema descriptor for updated_at field.
	workflowrunDescUpdatedAt := workflowrunFields[11].Descriptor()
	// workflowrun.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflowrun.DefaultUpdatedAt = workflowrunDescUpdatedAt.Default.(func() time.Time)
	// workflowrun.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workflowrun.UpdateDefaultUpdatedAt = workflowrunDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workflowrunDescID is the schema descriptor for id field.
	workflowrunDescID := workflowrunFields[0].Descriptor()
	// workflowrun.DefaultID holds the default value on creation for the id field.
	workflowrun.DefaultID = workflowrunDescID.Default.(func() uuid.UUID)
}
