// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/spacefleet/ent/predicate"
	"github.com/spacefleet/spacefleet/ent/tektoninstallation"
)

// TektonInstallationDelete is the builder for deleting a TektonInstallation entity.
type TektonInstallationDelete struct {
	config
	hooks    []Hook
	mutation *TektonInstallationMutation
}

// Where appends a list predicates to the TektonInstallationDelete builder.
func (_d *TektonInstallationDelete) Where(ps ...predicate.TektonInstallation) *TektonInstallationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TektonInstallationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TektonInstallationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TektonInstallationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tektoninstallation.Table, sqlgraph.NewFieldSpec(tektoninstallation.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TektonInstallationDeleteOne is the builder for deleting a single TektonInstallation entity.
type TektonInstallationDeleteOne struct {
	_d *TektonInstallationDelete
}

// Where appends a list predicates to the TektonInstallationDelete builder.
func (_d *TektonInstallationDeleteOne) Where(ps ...predicate.TektonInstallation) *TektonInstallationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TektonInstallationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tektoninstallation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TektonInstallationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
