// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/spacefleet/spacefleet/ent/predicate"
	"github.com/spacefleet/spacefleet/ent/variable"
)

// VariableUpdate is the builder for updating Variable entities.
type VariableUpdate struct {
	config
	hooks    []Hook
	mutation *VariableMutation
}

// Where appends a list predicates to the VariableUpdate builder.
func (_u *VariableUpdate) Where(ps ...predicate.Variable) *VariableUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VariableUpdate) SetName(v string) *VariableUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VariableUpdate) SetNillableName(v *string) *VariableUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSensitive sets the "sensitive" field.
func (_u *VariableUpdate) SetSensitive(v bool) *VariableUpdate {
	_u.mutation.SetSensitive(v)
	return _u
}

// SetNillableSensitive sets the "sensitive" field if the given value is not nil.
func (_u *VariableUpdate) SetNillableSensitive(v *bool) *VariableUpdate {
	if v != nil {
		_u.SetSensitive(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *VariableUpdate) SetValue(v string) *VariableUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *VariableUpdate) SetNillableValue(v *string) *VariableUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *VariableUpdate) ClearValue() *VariableUpdate {
	_u.mutation.ClearValue()
	return _u
}

// SetEncryptedValue sets the "encrypted_value" field.
func (_u *VariableUpdate) SetEncryptedValue(v []byte) *VariableUpdate {
	_u.mutation.SetEncryptedValue(v)
	return _u
}

// ClearEncryptedValue clears the value of the "encrypted_value" field.
func (_u *VariableUpdate) ClearEncryptedValue() *VariableUpdate {
	_u.mutation.ClearEncryptedValue()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VariableUpdate) SetUpdatedAt(v time.Time) *VariableUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VariableMutation object of the builder.
func (_u *VariableUpdate) Mutation() *VariableMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VariableUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VariableUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VariableUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VariableUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VariableUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := variable.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VariableUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := variable.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Variable.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variable.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variable.application"`)
	}
	return nil
}

func (_u *VariableUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(variable.Table, variable.Columns, sqlgraph.NewFieldSpec(variable.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ComponentIDCleared() {
		_spec.ClearField(variable.FieldComponentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(variable.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sensitive(); ok {
		_spec.SetField(variable.FieldSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(variable.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(variable.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedValue(); ok {
		_spec.SetField(variable.FieldEncryptedValue, field.TypeBytes, value)
	}
	if _u.mutation.EncryptedValueCleared() {
		_spec.ClearField(variable.FieldEncryptedValue, field.TypeBytes)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(variable.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{variable.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VariableUpdateOne is the builder for updating a single Variable entity.
type VariableUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VariableMutation
}

// SetName sets the "name" field.
func (_u *VariableUpdateOne) SetName(v string) *VariableUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VariableUpdateOne) SetNillableName(v *string) *VariableUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSensitive sets the "sensitive" field.
func (_u *VariableUpdateOne) SetSensitive(v bool) *VariableUpdateOne {
	_u.mutation.SetSensitive(v)
	return _u
}

// SetNillableSensitive sets the "sensitive" field if the given value is not nil.
func (_u *VariableUpdateOne) SetNillableSensitive(v *bool) *VariableUpdateOne {
	if v != nil {
		_u.SetSensitive(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *VariableUpdateOne) SetValue(v string) *VariableUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *VariableUpdateOne) SetNillableValue(v *string) *VariableUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *VariableUpdateOne) ClearValue() *VariableUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// SetEncryptedValue sets the "encrypted_value" field.
func (_u *VariableUpdateOne) SetEncryptedValue(v []byte) *VariableUpdateOne {
	_u.mutation.SetEncryptedValue(v)
	return _u
}

// ClearEncryptedValue clears the value of the "encrypted_value" field.
func (_u *VariableUpdateOne) ClearEncryptedValue() *VariableUpdateOne {
	_u.mutation.ClearEncryptedValue()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VariableUpdateOne) SetUpdatedAt(v time.Time) *VariableUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VariableMutation object of the builder.
func (_u *VariableUpdateOne) Mutation() *VariableMutation {
	return _u.mutation
}

// Where appends a list predicates to the VariableUpdate builder.
func (_u *VariableUpdateOne) Where(ps ...predicate.Variable) *VariableUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VariableUpdateOne) Select(field string, fields ...string) *VariableUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Variable entity.
func (_u *VariableUpdateOne) Save(ctx context.Context) (*Variable, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VariableUpdateOne) SaveX(ctx context.Context) *Variable {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VariableUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VariableUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VariableUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := variable.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VariableUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := variable.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Variable.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variable.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Variable.application"`)
	}
	return nil
}

func (_u *VariableUpdateOne) sqlSave(ctx context.Context) (_node *Variable, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(variable.Table, variable.Columns, sqlgraph.NewFieldSpec(variable.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Variable.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, variable.FieldID)
		for _, f := range fields {
			if !variable.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != variable.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ComponentIDCleared() {
		_spec.ClearField(variable.FieldComponentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(variable.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sensitive(); ok {
		_spec.SetField(variable.FieldSensitive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(variable.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(variable.FieldValue, field.TypeString)
	}
	if value, ok := _u.mutation.EncryptedValue(); ok {
		_spec.SetField(variable.FieldEncryptedValue, field.TypeBytes, value)
	}
	if _u.mutation.EncryptedValueCleared() {
		_spec.ClearField(variable.FieldEncryptedValue, field.TypeBytes)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(variable.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Variable{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{variable.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
