// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/component"
	"github.com/spacefleet/spacefleet/ent/predicate"
	"github.com/spacefleet/spacefleet/ent/workflowstage"
)

// WorkflowStageUpdate is the builder for updating WorkflowStage entities.
type WorkflowStageUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowStageMutation
}

// Where appends a list predicates to the WorkflowStageUpdate builder.
func (_u *WorkflowStageUpdate) Where(ps ...predicate.WorkflowStage) *WorkflowStageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WorkflowStageUpdate) SetName(v string) *WorkflowStageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkflowStageUpdate) SetNillableName(v *string) *WorkflowStageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOrdinal sets the "ordinal" field.
func (_u *WorkflowStageUpdate) SetOrdinal(v int) *WorkflowStageUpdate {
	_u.mutation.ResetOrdinal()
	_u.mutation.SetOrdinal(v)
	return _u
}

// SetNillableOrdinal sets the "ordinal" field if the given value is not nil.
func (_u *WorkflowStageUpdate) SetNillableOrdinal(v *int) *WorkflowStageUpdate {
	if v != nil {
		_u.SetOrdinal(*v)
	}
	return _u
}

// AddOrdinal adds value to the "ordinal" field.
func (_u *WorkflowStageUpdate) AddOrdinal(v int) *WorkflowStageUpdate {
	_u.mutation.AddOrdinal(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowStageUpdate) SetUpdatedAt(v time.Time) *WorkflowStageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the Component entity by IDs.
func (_u *WorkflowStageUpdate) AddComponentIDs(ids ...uuid.UUID) *WorkflowStageUpdate {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the Component entity.
func (_u *WorkflowStageUpdate) AddComponents(v ...*Component) *WorkflowStageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// Mutation returns the WorkflowStageMutation object of the builder.
func (_u *WorkflowStageUpdate) Mutation() *WorkflowStageMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the Component entity.
func (_u *WorkflowStageUpdate) ClearComponents() *WorkflowStageUpdate {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to Component entities by IDs.
func (_u *WorkflowStageUpdate) RemoveComponentIDs(ids ...uuid.UUID) *WorkflowStageUpdate {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to Component entities.
func (_u *WorkflowStageUpdate) RemoveComponents(v ...*Component) *WorkflowStageUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowStageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowStageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowStageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowStageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowStageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflowstage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowStageUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workflowstage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WorkflowStage.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowStage.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowStage.application"`)
	}
	return nil
}

func (_u *WorkflowStageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowstage.Table, workflowstage.Columns, sqlgraph.NewFieldSpec(workflowstage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workflowstage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ordinal(); ok {
		_spec.SetField(workflowstage.FieldOrdinal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrdinal(); ok {
		_spec.AddField(workflowstage.FieldOrdinal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowstage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowstage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowStageUpdateOne is the builder for updating a single WorkflowStage entity.
type WorkflowStageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowStageMutation
}

// SetName sets the "name" field.
func (_u *WorkflowStageUpdateOne) SetName(v string) *WorkflowStageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkflowStageUpdateOne) SetNillableName(v *string) *WorkflowStageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetOrdinal sets the "ordinal" field.
func (_u *WorkflowStageUpdateOne) SetOrdinal(v int) *WorkflowStageUpdateOne {
	_u.mutation.ResetOrdinal()
	_u.mutation.SetOrdinal(v)
	return _u
}

// SetNillableOrdinal sets the "ordinal" field if the given value is not nil.
func (_u *WorkflowStageUpdateOne) SetNillableOrdinal(v *int) *WorkflowStageUpdateOne {
	if v != nil {
		_u.SetOrdinal(*v)
	}
	return _u
}

// AddOrdinal adds value to the "ordinal" field.
func (_u *WorkflowStageUpdateOne) AddOrdinal(v int) *WorkflowStageUpdateOne {
	_u.mutation.AddOrdinal(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowStageUpdateOne) SetUpdatedAt(v time.Time) *WorkflowStageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the Component entity by IDs.
func (_u *WorkflowStageUpdateOne) AddComponentIDs(ids ...uuid.UUID) *WorkflowStageUpdateOne {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the Component entity.
func (_u *WorkflowStageUpdateOne) AddComponents(v ...*Component) *WorkflowStageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// Mutation returns the WorkflowStageMutation object of the builder.
func (_u *WorkflowStageUpdateOne) Mutation() *WorkflowStageMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the Component entity.
func (_u *WorkflowStageUpdateOne) ClearComponents() *WorkflowStageUpdateOne {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to Component entities by IDs.
func (_u *WorkflowStageUpdateOne) RemoveComponentIDs(ids ...uuid.UUID) *WorkflowStageUpdateOne {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to Component entities.
func (_u *WorkflowStageUpdateOne) RemoveComponents(v ...*Component) *WorkflowStageUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// Where appends a list predicates to the WorkflowStageUpdate builder.
func (_u *WorkflowStageUpdateOne) Where(ps ...predicate.WorkflowStage) *WorkflowStageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowStageUpdateOne) Select(field string, fields ...string) *WorkflowStageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowStage entity.
func (_u *WorkflowStageUpdateOne) Save(ctx context.Context) (*WorkflowStage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowStageUpdateOne) SaveX(ctx context.Context) *WorkflowStage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowStageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowStageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowStageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflowstage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowStageUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workflowstage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WorkflowStage.name": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowStage.organization"`)
	}
	if _u.mutation.ApplicationCleared() && len(_u.mutation.ApplicationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowStage.application"`)
	}
	return nil
}

func (_u *WorkflowStageUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowStage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowstage.Table, workflowstage.Columns, sqlgraph.NewFieldSpec(workflowstage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowStage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowstage.FieldID)
		for _, f := range fields {
			if !workflowstage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowstage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workflowstage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ordinal(); ok {
		_spec.SetField(workflowstage.FieldOrdinal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrdinal(); ok {
		_spec.AddField(workflowstage.FieldOrdinal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowstage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   workflowstage.ComponentsTable,
			Columns: []string{workflowstage.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkflowStage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowstage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
