// Code generated by ent, DO NOT EDIT.

package application

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the application type in the database.
	Label = "application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImported holds the string denoting the imported field in the database.
	FieldImported = "imported"
	// FieldDriftIntervalMinutes holds the string denoting the drift_interval_minutes field in the database.
	FieldDriftIntervalMinutes = "drift_interval_minutes"
	// FieldPushTrigger holds the string denoting the push_trigger field in the database.
	FieldPushTrigger = "push_trigger"
	// FieldPrPlans holds the string denoting the pr_plans field in the database.
	FieldPrPlans = "pr_plans"
	// FieldRunnerClusterID holds the string denoting the runner_cluster_id field in the database.
	FieldRunnerClusterID = "runner_cluster_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeRunnerCluster holds the string denoting the runner_cluster edge name in mutations.
	EdgeRunnerCluster = "runner_cluster"
	// Table holds the table name of the application in the database.
	Table = "applications"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "applications"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
	// RunnerClusterTable is the table that holds the runner_cluster relation/edge.
	RunnerClusterTable = "applications"
	// RunnerClusterInverseTable is the table name for the Cluster entity.
	// It exists in this package in order to avoid circular dependency with the "cluster" package.
	RunnerClusterInverseTable = "clusters"
	// RunnerClusterColumn is the table column denoting the runner_cluster relation/edge.
	RunnerClusterColumn = "runner_cluster_id"
)

// Columns holds all SQL columns for application fields.
var Columns = []string{
	FieldID,
	FieldOrganizationID,
	FieldName,
	FieldImported,
	FieldDriftIntervalMinutes,
	FieldPushTrigger,
	FieldPrPlans,
	FieldRunnerClusterID,
	FieldGroupID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultImported holds the default value on creation for the "imported" field.
	DefaultImported bool
	// DefaultDriftIntervalMinutes holds the default value on creation for the "drift_interval_minutes" field.
	DefaultDriftIntervalMinutes int
	// DriftIntervalMinutesValidator is a validator for the "drift_interval_minutes" field. It is called by the builders before save.
	DriftIntervalMinutesValidator func(int) error
	// DefaultPushTrigger holds the default value on creation for the "push_trigger" field.
	DefaultPushTrigger string
	// DefaultPrPlans holds the default value on creation for the "pr_plans" field.
	DefaultPrPlans bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Application queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByImported orders the results by the imported field.
func ByImported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImported, opts...).ToFunc()
}

// ByDriftIntervalMinutes orders the results by the drift_interval_minutes field.
func ByDriftIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDriftIntervalMinutes, opts...).ToFunc()
}

// ByPushTrigger orders the results by the push_trigger field.
func ByPushTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPushTrigger, opts...).ToFunc()
}

// ByPrPlans orders the results by the pr_plans field.
func ByPrPlans(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrPlans, opts...).ToFunc()
}

// ByRunnerClusterID orders the results by the runner_cluster_id field.
func ByRunnerClusterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunnerClusterID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunnerClusterField orders the results by runner_cluster field.
func ByRunnerClusterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunnerClusterStep(), sql.OrderByField(field, opts...))
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
	)
}
func newRunnerClusterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunnerClusterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RunnerClusterTable, RunnerClusterColumn),
	)
}
