{{- include "spacefleet.validate" . -}}
{{- $manageDB := eq (include "spacefleet.manageDatabaseSecret" .) "true" -}}
{{- if $manageDB }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spacefleet.envSecretName" . }}
  labels:
    {{- include "spacefleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "spacefleet.databaseURL" . | quote }}
{{- end }}
