{{- include "spacefleet.validate" . -}}
{{- if eq (include "spacefleet.manageEnvSecret" .) "true" }}
{{- $manageDB := eq (include "spacefleet.manageDatabaseSecret" .) "true" -}}
{{- $secrets := .Values.config.secrets | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spacefleet.envSecretName" . }}
  labels:
    {{- include "spacefleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $manageDB }}
  DATABASE_URL: {{ include "spacefleet.databaseURL" . | quote }}
  {{- end }}
  {{- with $secrets.secretKey }}
  SPACEFLEET_SECRET_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
