{{- include "spacefleet.validate" . -}}
{{- $manageDB := eq (include "spacefleet.manageDatabaseSecret" .) "true" -}}
{{- $manageRedis := eq (include "spacefleet.manageRedisSecret" .) "true" -}}
{{- if or $manageDB $manageRedis }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spacefleet.envSecretName" . }}
  labels:
    {{- include "spacefleet.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $manageDB }}
  DATABASE_URL: {{ include "spacefleet.databaseURL" . | quote }}
  {{- end }}
  {{- if $manageRedis }}
  REDIS_URL: {{ include "spacefleet.redisURL" . | quote }}
  {{- end }}
{{- end }}
