// Code generated by ent, DO NOT EDIT.

package component

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/spacefleet/spacefleet/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldLTE(FieldID, id))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldOrganizationID, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldApplicationID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldName, v))
}

// ContinueOnFailure applies equality check predicate on the "continue_on_failure" field. It's identical to ContinueOnFailureEQ.
func ContinueOnFailure(v bool) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldContinueOnFailure, v))
}

// RequiresApproval applies equality check predicate on the "requires_approval" field. It's identical to RequiresApprovalEQ.
func RequiresApproval(v bool) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldRequiresApproval, v))
}

// TargetClusterID applies equality check predicate on the "target_cluster_id" field. It's identical to TargetClusterIDEQ.
func TargetClusterID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldTargetClusterID, v))
}

// TargetNamespace applies equality check predicate on the "target_namespace" field. It's identical to TargetNamespaceEQ.
func TargetNamespace(v string) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldTargetNamespace, v))
}

// ChartCredentialID applies equality check predicate on the "chart_credential_id" field. It's identical to ChartCredentialIDEQ.
func ChartCredentialID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldChartCredentialID, v))
}

// GithubInstallationID applies equality check predicate on the "github_installation_id" field. It's identical to GithubInstallationIDEQ.
func GithubInstallationID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldGroupID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldApplicationID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Component {
	return predicate.Component(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Component {
	return predicate.Component(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Component {
	return predicate.Component(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Component {
	return predicate.Component(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Component {
	return predicate.Component(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Component {
	return predicate.Component(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Component {
	return predicate.Component(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Component {
	return predicate.Component(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Component {
	return predicate.Component(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldType, vs...))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldConfig))
}

// DependsOnIsNil applies the IsNil predicate on the "depends_on" field.
func DependsOnIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldDependsOn))
}

// DependsOnNotNil applies the NotNil predicate on the "depends_on" field.
func DependsOnNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldDependsOn))
}

// ContinueOnFailureEQ applies the EQ predicate on the "continue_on_failure" field.
func ContinueOnFailureEQ(v bool) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldContinueOnFailure, v))
}

// ContinueOnFailureNEQ applies the NEQ predicate on the "continue_on_failure" field.
func ContinueOnFailureNEQ(v bool) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldContinueOnFailure, v))
}

// RequiresApprovalEQ applies the EQ predicate on the "requires_approval" field.
func RequiresApprovalEQ(v bool) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldRequiresApproval, v))
}

// RequiresApprovalNEQ applies the NEQ predicate on the "requires_approval" field.
func RequiresApprovalNEQ(v bool) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldRequiresApproval, v))
}

// TargetClusterIDEQ applies the EQ predicate on the "target_cluster_id" field.
func TargetClusterIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldTargetClusterID, v))
}

// TargetClusterIDNEQ applies the NEQ predicate on the "target_cluster_id" field.
func TargetClusterIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldTargetClusterID, v))
}

// TargetClusterIDIn applies the In predicate on the "target_cluster_id" field.
func TargetClusterIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldTargetClusterID, vs...))
}

// TargetClusterIDNotIn applies the NotIn predicate on the "target_cluster_id" field.
func TargetClusterIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldTargetClusterID, vs...))
}

// TargetClusterIDIsNil applies the IsNil predicate on the "target_cluster_id" field.
func TargetClusterIDIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldTargetClusterID))
}

// TargetClusterIDNotNil applies the NotNil predicate on the "target_cluster_id" field.
func TargetClusterIDNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldTargetClusterID))
}

// TargetNamespaceEQ applies the EQ predicate on the "target_namespace" field.
func TargetNamespaceEQ(v string) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldTargetNamespace, v))
}

// TargetNamespaceNEQ applies the NEQ predicate on the "target_namespace" field.
func TargetNamespaceNEQ(v string) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldTargetNamespace, v))
}

// TargetNamespaceIn applies the In predicate on the "target_namespace" field.
func TargetNamespaceIn(vs ...string) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldTargetNamespace, vs...))
}

// TargetNamespaceNotIn applies the NotIn predicate on the "target_namespace" field.
func TargetNamespaceNotIn(vs ...string) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldTargetNamespace, vs...))
}

// TargetNamespaceGT applies the GT predicate on the "target_namespace" field.
func TargetNamespaceGT(v string) predicate.Component {
	return predicate.Component(sql.FieldGT(FieldTargetNamespace, v))
}

// TargetNamespaceGTE applies the GTE predicate on the "target_namespace" field.
func TargetNamespaceGTE(v string) predicate.Component {
	return predicate.Component(sql.FieldGTE(FieldTargetNamespace, v))
}

// TargetNamespaceLT applies the LT predicate on the "target_namespace" field.
func TargetNamespaceLT(v string) predicate.Component {
	return predicate.Component(sql.FieldLT(FieldTargetNamespace, v))
}

// TargetNamespaceLTE applies the LTE predicate on the "target_namespace" field.
func TargetNamespaceLTE(v string) predicate.Component {
	return predicate.Component(sql.FieldLTE(FieldTargetNamespace, v))
}

// TargetNamespaceContains applies the Contains predicate on the "target_namespace" field.
func TargetNamespaceContains(v string) predicate.Component {
	return predicate.Component(sql.FieldContains(FieldTargetNamespace, v))
}

// TargetNamespaceHasPrefix applies the HasPrefix predicate on the "target_namespace" field.
func TargetNamespaceHasPrefix(v string) predicate.Component {
	return predicate.Component(sql.FieldHasPrefix(FieldTargetNamespace, v))
}

// TargetNamespaceHasSuffix applies the HasSuffix predicate on the "target_namespace" field.
func TargetNamespaceHasSuffix(v string) predicate.Component {
	return predicate.Component(sql.FieldHasSuffix(FieldTargetNamespace, v))
}

// TargetNamespaceIsNil applies the IsNil predicate on the "target_namespace" field.
func TargetNamespaceIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldTargetNamespace))
}

// TargetNamespaceNotNil applies the NotNil predicate on the "target_namespace" field.
func TargetNamespaceNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldTargetNamespace))
}

// TargetNamespaceEqualFold applies the EqualFold predicate on the "target_namespace" field.
func TargetNamespaceEqualFold(v string) predicate.Component {
	return predicate.Component(sql.FieldEqualFold(FieldTargetNamespace, v))
}

// TargetNamespaceContainsFold applies the ContainsFold predicate on the "target_namespace" field.
func TargetNamespaceContainsFold(v string) predicate.Component {
	return predicate.Component(sql.FieldContainsFold(FieldTargetNamespace, v))
}

// ChartCredentialIDEQ applies the EQ predicate on the "chart_credential_id" field.
func ChartCredentialIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldChartCredentialID, v))
}

// ChartCredentialIDNEQ applies the NEQ predicate on the "chart_credential_id" field.
func ChartCredentialIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldChartCredentialID, v))
}

// ChartCredentialIDIn applies the In predicate on the "chart_credential_id" field.
func ChartCredentialIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldChartCredentialID, vs...))
}

// ChartCredentialIDNotIn applies the NotIn predicate on the "chart_credential_id" field.
func ChartCredentialIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldChartCredentialID, vs...))
}

// ChartCredentialIDIsNil applies the IsNil predicate on the "chart_credential_id" field.
func ChartCredentialIDIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldChartCredentialID))
}

// ChartCredentialIDNotNil applies the NotNil predicate on the "chart_credential_id" field.
func ChartCredentialIDNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldChartCredentialID))
}

// GithubInstallationIDEQ applies the EQ predicate on the "github_installation_id" field.
func GithubInstallationIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDNEQ applies the NEQ predicate on the "github_installation_id" field.
func GithubInstallationIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDIn applies the In predicate on the "github_installation_id" field.
func GithubInstallationIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDNotIn applies the NotIn predicate on the "github_installation_id" field.
func GithubInstallationIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDIsNil applies the IsNil predicate on the "github_installation_id" field.
func GithubInstallationIDIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldGithubInstallationID))
}

// GithubInstallationIDNotNil applies the NotNil predicate on the "github_installation_id" field.
func GithubInstallationIDNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldGithubInstallationID))
}

// PositionIsNil applies the IsNil predicate on the "position" field.
func PositionIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldPosition))
}

// PositionNotNil applies the NotNil predicate on the "position" field.
func PositionNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldPosition))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.Component {
	return predicate.Component(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.Component {
	return predicate.Component(sql.FieldNotNull(FieldGroupID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Component {
	return predicate.Component(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Component {
	return predicate.Component(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Component {
	return predicate.Component(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.Application) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetCluster applies the HasEdge predicate on the "target_cluster" edge.
func HasTargetCluster() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TargetClusterTable, TargetClusterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetClusterWith applies the HasEdge predicate on the "target_cluster" edge with a given conditions (other predicates).
func HasTargetClusterWith(preds ...predicate.Cluster) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newTargetClusterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChartCredential applies the HasEdge predicate on the "chart_credential" edge.
func HasChartCredential() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ChartCredentialTable, ChartCredentialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChartCredentialWith applies the HasEdge predicate on the "chart_credential" edge with a given conditions (other predicates).
func HasChartCredentialWith(preds ...predicate.ChartCredential) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newChartCredentialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGithubInstallation applies the HasEdge predicate on the "github_installation" edge.
func HasGithubInstallation() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GithubInstallationTable, GithubInstallationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGithubInstallationWith applies the HasEdge predicate on the "github_installation" edge with a given conditions (other predicates).
func HasGithubInstallationWith(preds ...predicate.GitHubInstallation) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newGithubInstallationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.ComponentGroup) predicate.Component {
	return predicate.Component(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Component) predicate.Component {
	return predicate.Component(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Component) predicate.Component {
	return predicate.Component(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Component) predicate.Component {
	return predicate.Component(sql.NotPredicates(p))
}
