// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cluster is the predicate function for cluster builders.
type Cluster func(*sql.Selector)

// Invitation is the predicate function for invitation builders.
type Invitation func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
